(()=>{
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const hdr=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:hdr(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||('Request failed '+r.status));return d}
  const sx=v=>esc(String(v??''));
  let cases=[],commitments=[],deadlines=[],outages=[];
  function memberName(){return window.VMUSF_AUTH?.user?.user_metadata?.display_name||window.VMUSF_AUTH?.user?.email?.split('@')[0]||'there'}
  async function load(){if(!uid()){cases=[];commitments=[];deadlines=[];outages=[];return}const id=encodeURIComponent(uid());try{[cases,commitments,deadlines,outages]=await Promise.all([
      api('vmusf_support_cases?select=id,case_reference,title,service,status,journey_stage,next_action,next_action_at,updated_at&user_id=eq.'+id+'&status=not.in.(closed,resolved)&order=updated_at.desc&limit=20'),
      api('vmusf_case_commitments?select=id,case_id,commitment_type,description,promised_at,due_at,due_window_start,due_window_end,status,confirmation_required&user_id=eq.'+id+'&status=eq.pending&order=due_at.asc.nullslast&limit=30'),
      api('vmusf_case_deadlines?select=id,case_id,label,due_at,status,source_kind,deadline_type&user_id=eq.'+id+'&status=eq.active&order=due_at.asc&limit=30'),
      api('outage_reports?select=id,postcode_area,service,started_at,status,created_at&user_id=eq.'+id+'&status=neq.resolved&order=created_at.desc&limit=10')
    ])}catch(e){console.warn('Adaptive home',e)}}
  const caseBy=id=>cases.find(c=>c.id===id);
  const when=iso=>{if(!iso)return'';const d=new Date(iso),now=new Date(),mins=Math.round((d-now)/60000),abs=Math.abs(mins);if(abs<2)return'now';if(mins<0){if(abs<60)return abs+' minutes overdue';if(abs<1440)return Math.round(abs/60)+' hours overdue';return Math.round(abs/1440)+' days overdue'}if(mins<60)return'in '+mins+' minutes';if(mins<1440)return'in '+Math.round(mins/60)+' hours';return d.toLocaleDateString('en-GB',{day:'numeric',month:'short'})+' at '+d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})};
  function stageBars(c){const order=['diagnosis','provider_contact','monitoring','complaint','resolved'];let i=Math.max(0,order.indexOf(String(c?.journey_stage||'diagnosis')));return `<div class="vm-journey-mini" aria-label="Case progress">${order.slice(0,4).map((_,x)=>`<span class="${x<i?'done':x===i?'now':''}"></span>`).join('')}</div>`}
  function priority(){const now=Date.now();const pending=commitments.filter(x=>x.due_at).sort((a,b)=>new Date(a.due_at)-new Date(b.due_at));const overdue=pending.find(x=>new Date(x.due_at).getTime()<now);if(overdue){const c=caseBy(overdue.case_id);return{kind:'overdue',kicker:'Virgin promise overdue',title:overdue.commitment_type==='callback'?'Did Virgin call you?':'Did Virgin do what they promised?',text:`${overdue.description||'A provider promise'} was due ${when(overdue.due_at)}.`,case:c,commitment:overdue,buttons:'promise'}}
    const soon=pending.find(x=>new Date(x.due_at).getTime()-now<=24*3600000);if(soon){const c=caseBy(soon.case_id);return{kind:'today',kicker:'Due soon',title:soon.commitment_type==='callback'?'Virgin is due to call you':'A Virgin promise is due soon',text:`${soon.description||'Provider promise'} · ${when(soon.due_at)}.`,case:c,commitment:soon,buttons:'promise'}}
    const out=outages[0];if(out){return{kind:'outage',kicker:'Your service incident is still open',title:`${String(out.service||'Service').replace(/^./,x=>x.toUpperCase())} problem still being tracked`,text:`Started ${new Date(out.started_at||out.created_at).toLocaleString('en-GB')}. Check status before doing more troubleshooting.`,outage:out,buttons:'outage'}}
    const dl=deadlines.find(x=>new Date(x.due_at).getTime()-now<=48*3600000);if(dl){const c=caseBy(dl.case_id);return{kind:'today',kicker:'Case deadline approaching',title:dl.label||'A case deadline is approaching',text:`Due ${when(dl.due_at)}. ${dl.source_kind==='provider_promise'?'This is a provider promise, not a regulator deadline.':'VMUSF is tracking this separately from provider promises.'}`,case:c,buttons:'case'}}
    const c=cases.find(x=>x.next_action)||cases[0];if(c)return{kind:'case',kicker:'Pick up where you left off',title:c.next_action||c.title,text:`${c.case_reference||'Your case'} · ${c.title}`,case:c,buttons:'case'};
    return null}
  function markup(p){if(!p)return'';let acts='';if(p.buttons==='promise')acts=`<button class="btn primary" data-adapt="promise-done" data-id="${sx(p.commitment.id)}">Yes, they did</button><button class="btn" data-adapt="promise-missed" data-id="${sx(p.commitment.id)}">No, they didn't</button>`;else if(p.buttons==='outage')acts=`<button class="btn primary" data-r="outages">Check status</button><button class="btn" data-r="help">Continue troubleshooting</button>`;else acts=`<button class="btn primary" data-r="account">Open my case</button><button class="btn" data-r="help">Continue with Guided Help</button>`;return `<section class="vm-adaptive" data-kind="${sx(p.kind)}" aria-label="Your next useful step"><div class="vm-adaptive-inner"><div><div class="vm-adaptive-kicker"><span class="vm-adaptive-dot"></span>Hi ${sx(memberName())} · ${sx(p.kicker)}</div><h2>${sx(p.title)}</h2><p>${sx(p.text)}</p>${p.case?stageBars(p.case):''}</div><div class="vm-adaptive-actions">${acts}</div></div></section>`}
  function inject(){document.querySelector('.vm-adaptive')?.remove();if(!uid())return;const p=priority();if(!p)return;const page=document.querySelector('.forum-page'),mast=page?.querySelector('.forum-mast');if(!mast)return;mast.insertAdjacentHTML('afterend',markup(p));bindLocal()}
  async function promise(id,done){const c=commitments.find(x=>x.id===id);if(!c)return;const now=new Date().toISOString();try{await api('vmusf_case_commitments?id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid()),{method:'PATCH',prefer:'return=minimal',body:{status:done?'fulfilled':'missed',confirmed_at:now,updated_at:now}});await api('vmusf_case_events',{method:'POST',prefer:'return=minimal',body:{case_id:c.case_id,user_id:uid(),event_type:done?'provider_promise_completed':'provider_promise_missed',label:done?'Provider promise completed':'Provider promise missed',details:{answer:c.description||c.commitment_type,commitment_id:c.id}}});if(!done)await api('vmusf_support_cases?id=eq.'+encodeURIComponent(c.case_id)+'&user_id=eq.'+encodeURIComponent(uid()),{method:'PATCH',prefer:'return=minimal',body:{status:'open',journey_stage:'provider_contact',next_action:'Virgin missed the promised action. Record what happened and decide the next contact or escalation step.',next_action_at:null,updated_at:now}});toastMsg(done?'Marked as completed.':'Marked as missed. Your case has been updated.');await load();inject()}catch(e){console.warn(e);toastMsg(e.message||'Could not update that promise.')}
  function bindLocal(){document.querySelectorAll('[data-adapt]').forEach(b=>b.onclick=e=>{e.preventDefault();promise(b.dataset.id,b.dataset.adapt==='promise-done')})}
  const mo=new MutationObserver(()=>{if((current==='home'||current==='community')&&!document.querySelector('.vm-adaptive'))inject()});mo.observe(document.body,{childList:true,subtree:true});
  window.addEventListener('vmusf-auth-changed',()=>load().then(inject));
  setTimeout(()=>load().then(inject),900);
})();