(()=>{
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const hdr=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:hdr(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||('Request failed '+r.status));return d}
  const sx=v=>esc(String(v??''));
  let cases=[],commitments=[],deadlines=[],outages=[];
  const DISMISS='vmusf-adaptive-dismissed-v1';
  function dismissed(){try{return JSON.parse(localStorage.getItem(DISMISS)||'{}')}catch{return{}}}
  function saveDismiss(key){const d=dismissed();d[key]=Date.now();try{localStorage.setItem(DISMISS,JSON.stringify(d))}catch{}}
  function memberName(){return window.VMUSF_AUTH?.user?.user_metadata?.display_name||window.VMUSF_AUTH?.user?.email?.split('@')[0]||'there'}
  async function load(){if(!uid()){cases=[];commitments=[];deadlines=[];outages=[];return}const id=encodeURIComponent(uid());try{[cases,commitments,deadlines,outages]=await Promise.all([
      api('vmusf_support_cases?select=id,case_reference,title,service,status,journey_stage,next_action,next_action_at,updated_at&user_id=eq.'+id+'&status=not.in.(closed,resolved)&order=updated_at.desc&limit=20'),
      api('vmusf_case_commitments?select=id,case_id,commitment_type,description,promised_at,due_at,due_window_start,due_window_end,status,confirmation_required&user_id=eq.'+id+'&status=eq.pending&order=due_at.asc.nullslast&limit=30'),
      api('vmusf_case_deadlines?select=id,case_id,label,due_at,status,source_kind,deadline_type&user_id=eq.'+id+'&status=eq.active&order=due_at.asc&limit=30'),
      api('outage_reports?select=id,postcode_area,service,started_at,status,created_at&user_id=eq.'+id+'&status=neq.resolved&order=created_at.desc&limit=10')
    ])}catch(e){console.warn('Adaptive home',e)}}
  const caseBy=id=>cases.find(c=>c.id===id);
  const when=iso=>{if(!iso)return'';const d=new Date(iso),now=new Date(),mins=Math.round((d-now)/60000),abs=Math.abs(mins);if(abs<2)return'now';if(mins<0){if(abs<60)return abs+' minutes overdue';if(abs<1440)return Math.round(abs/60)+' hours overdue';return Math.round(abs/1440)+' days overdue'}if(mins<60)return'in '+mins+' minutes';if(mins<1440)return'in '+Math.round(mins/60)+' hours';return d.toLocaleDateString('en-GB',{day:'numeric',month:'short'})+' at '+d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})};
  function priority(){const now=Date.now(),seen=dismissed(),fresh=k=>!seen[k]||Date.now()-seen[k]>12*3600000;const pending=commitments.filter(x=>x.due_at).sort((a,b)=>new Date(a.due_at)-new Date(b.due_at));const overdue=pending.find(x=>new Date(x.due_at).getTime()<now&&fresh('commitment:'+x.id));if(overdue){const c=caseBy(overdue.case_id);return{key:'commitment:'+overdue.id,kind:'overdue',kicker:'Virgin promise overdue',title:overdue.commitment_type==='callback'?'Did Virgin call you?':'Did Virgin do what they promised?',text:`${overdue.description||'A provider promise'} was due ${when(overdue.due_at)}.`,case:c,commitment:overdue,buttons:'promise'}}
    const soon=pending.find(x=>new Date(x.due_at).getTime()-now<=24*3600000&&fresh('commitment:'+x.id));if(soon){const c=caseBy(soon.case_id);return{key:'commitment:'+soon.id,kind:'today',kicker:'Due soon',title:soon.commitment_type==='callback'?'Virgin is due to call you':'A Virgin promise is due soon',text:`${soon.description||'Provider promise'} · ${when(soon.due_at)}.`,case:c,commitment:soon,buttons:'promise'}}
    const out=outages.find(x=>fresh('outage:'+x.id));if(out){return{key:'outage:'+out.id,kind:'outage',kicker:'Service incident open',title:`${String(out.service||'Service').replace(/^./,x=>x.toUpperCase())} problem still being tracked`,text:'Check status before doing more troubleshooting.',outage:out,buttons:'outage'}}
    const dl=deadlines.find(x=>new Date(x.due_at).getTime()-now<=24*3600000&&fresh('deadline:'+x.id));if(dl){const c=caseBy(dl.case_id);return{key:'deadline:'+dl.id,kind:'today',kicker:'Case deadline approaching',title:dl.label||'A case deadline is approaching',text:`Due ${when(dl.due_at)}.`,case:c,buttons:'case'}}
    return null
  }
  function markup(p){if(!p)return'';let acts='';if(p.buttons==='promise')acts=`<button class="btn primary" data-adapt="promise-done" data-id="${sx(p.commitment.id)}">Yes</button><button class="btn" data-adapt="promise-missed" data-id="${sx(p.commitment.id)}">No</button>`;else if(p.buttons==='outage')acts=`<button class="btn primary" data-r="outages">Check status</button>`;else acts=`<button class="btn primary" data-r="account">Open case</button>`;return `<section class="vm-adaptive" data-kind="${sx(p.kind)}" data-key="${sx(p.key)}" aria-label="Useful account update"><div class="vm-adaptive-inner"><div class="vm-adaptive-copy"><div class="vm-adaptive-kicker"><span class="vm-adaptive-dot"></span>${sx(p.kicker)}</div><h2>${sx(p.title)}</h2><p>${sx(p.text)}</p></div><div class="vm-adaptive-actions">${acts}</div><button class="vm-adaptive-dismiss" data-adapt-dismiss="${sx(p.key)}" aria-label="Dismiss this update">×</button></div></section>`}
  function inject(){document.querySelector('.vm-adaptive')?.remove();if(!uid())return;const p=priority();if(!p)return;const page=document.querySelector('.forum-page'),mast=page?.querySelector('.forum-mast');if(!mast)return;mast.insertAdjacentHTML('afterend',markup(p));bindLocal()}
  async function promise(id,done){const c=commitments.find(x=>x.id===id);if(!c)return;const now=new Date().toISOString();try{await api('vmusf_case_commitments?id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid()),{method:'PATCH',prefer:'return=minimal',body:{status:done?'fulfilled':'missed',confirmed_at:now,updated_at:now}});await api('vmusf_case_events',{method:'POST',prefer:'return=minimal',body:{case_id:c.case_id,user_id:uid(),event_type:done?'provider_promise_completed':'provider_promise_missed',label:done?'Provider promise completed':'Provider promise missed',details:{answer:c.description||c.commitment_type,commitment_id:c.id}}});if(!done)await api('vmusf_support_cases?id=eq.'+encodeURIComponent(c.case_id)+'&user_id=eq.'+encodeURIComponent(uid()),{method:'PATCH',prefer:'return=minimal',body:{status:'open',journey_stage:'provider_contact',next_action:'Virgin missed the promised action. Record what happened and decide the next contact or escalation step.',next_action_at:null,updated_at:now}});toastMsg(done?'Marked as completed.':'Marked as missed.');await load();inject()}catch(e){console.warn(e);toastMsg(e.message||'Could not update that promise.')}
  function bindLocal(){document.querySelectorAll('[data-adapt]').forEach(b=>b.onclick=e=>{e.preventDefault();promise(b.dataset.id,b.dataset.adapt==='promise-done')});document.querySelectorAll('[data-adapt-dismiss]').forEach(b=>b.onclick=e=>{e.preventDefault();saveDismiss(b.dataset.adaptDismiss);b.closest('.vm-adaptive')?.remove()})}
  const mo=new MutationObserver(()=>{if((current==='home'||current==='community')&&!document.querySelector('.vm-adaptive'))inject()});mo.observe(document.body,{childList:true,subtree:true});
  window.addEventListener('vmusf-auth-changed',()=>load().then(inject));
  setTimeout(()=>load().then(inject),900);
})();