(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const hdr=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:hdr(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||('Request failed ('+r.status+')'));return d}
  const sx=v=>esc(String(v??''));
  const GUEST='vmusf-assist-guest-v3';
  const VIRGIN_STATUS='https://www.virginmedia.com/help/check/status';
  let scenarios=[],knowledge=null,busy=false;
  let session=fresh();
  function fresh(){return {scenario:null,questions:[],index:0,answers:{},caseRow:null,opening:'',phase:'start'}}
  const name=()=>window.VMUSF_AUTH?.user?.user_metadata?.display_name||window.VMUSF_AUTH?.user?.email?.split('@')[0]||localStorage.getItem('vmusf-assist-name')||'';
  async function loadScenarios(){if(scenarios.length)return scenarios;try{scenarios=await api('vmusf_scenarios?select=scenario_key,domain,title,description,example_utterances,trigger_terms,required_facts,workflow_key,authority_scope&active=eq.true&order=priority.desc,title.asc')||[]}catch(e){console.warn('Assist scenarios',e);scenarios=[]}return scenarios}
  async function loadKnowledge(){if(knowledge)return knowledge;try{knowledge=await api('vmusf_knowledge_chunks?select=heading,content,device,category,keywords,authority&verified=eq.true&order=updated_at.desc&limit=120')||[]}catch(e){console.warn('Assist knowledge',e);knowledge=[]}return knowledge}
  function words(t){return String(t||'').toLowerCase().replace(/[^a-z0-9£. ]+/g,' ').split(/\s+/).filter(x=>x.length>2)}
  function classify(text){const w=words(text);let best=null,score=0;for(const s of scenarios){let n=0;for(const term of (s.trigger_terms||[])){const z=String(term).toLowerCase();if(text.toLowerCase().includes(z))n+=z.includes(' ')?5:3}for(const ex of (s.example_utterances||[])){const ew=words(ex);n+=ew.filter(x=>w.includes(x)).length*.6}if(n>score){score=n;best=s}}return score>=1.5?best:null}
  async function questionsFor(key){try{return await api('vmusf_scenario_questions?select=question_key,prompt,why_it_matters,answer_type,options,required,conditions,creates_event_type,creates_deadline_kind,sort_order&scenario_key=eq.'+encodeURIComponent(key)+'&active=eq.true&order=sort_order.asc')||[]}catch{return[]}}
  function technical(s,text=''){const v=((s?.domain||'')+' '+(s?.scenario_key||'')+' '+text).toLowerCase();return /(broadband|wifi|wi-fi|internet|hub|tv|television|phone|landline|voice|connection|speed|disconnect|offline|outage|fault)/.test(v)}
  function statusQuestions(){return [{question_key:'__postcode_area',prompt:'Before we troubleshoot anything in your home, what is your postcode area?',why_it_matters:'I’ll use only the broad area to check whether other VMUSF members are reporting the same service problem.',required:true},{question_key:'__virgin_status',prompt:`Now check Virgin’s official service status. <a href="${VIRGIN_STATUS}" target="_blank" rel="noopener noreferrer">Open Virgin service status</a><br><br>What does Virgin show?`,options:['Virgin reports an outage','No issue shown','I could not check'],required:true}]}
  function bubble(role,html){return `<div class="assist-bubble ${role}">${html}</div>`}
  function greeting(){const n=name();if(uid())return bubble('bot',`<b>Hi${n?', '+sx(n):''}. What’s happened?</b><p>Just explain it normally. I’ll ask what I need, keep the case organised, and you can keep talking to me afterwards.</p>`);if(n)return bubble('bot',`<b>Hi ${sx(n)}. What’s gone wrong?</b><p>Tell me in your own words. You can keep chatting without an account.</p>`);return bubble('bot',`<b>Hi. What should I call you?</b><p>Then tell me what’s gone wrong with your Virgin service.</p>`)}
  function helpPage(){return head('VMUSF Assist','Tell me what happened.','','One conversation. I’ll ask what matters, remember the route, and keep helping instead of stopping after the first answer.')+`<section class="assist-shell"><div class="assist-main"><div id="assist-log" class="assist-log" aria-live="polite">${greeting()}</div><form id="assist-form" class="assist-compose"><label for="assist-input">Type here</label><textarea id="assist-input" rows="3" maxlength="2500" placeholder="For example: My Wi-Fi keeps dropping upstairs"></textarea><div class="actions"><button class="btn primary" type="submit">Send</button><button class="btn" type="button" data-a="assist-new">Start a different problem</button><button class="btn" type="button" data-a="assist-my-cases">My cases</button></div><small>Do not enter passwords, security answers or full payment-card details.</small></form></div></section></div>`}
  P.help=helpPage;
  function add(role,html){const l=document.getElementById('assist-log');if(!l)return;l.insertAdjacentHTML('beforeend',bubble(role,html));l.scrollTop=l.scrollHeight}
  function reset(){session=fresh();if(!uid())localStorage.removeItem(GUEST);const l=document.getElementById('assist-log');if(l)l.innerHTML=greeting()}
  async function createCase(s,text){if(!uid())return null;try{const rows=await api('vmusf_support_cases',{method:'POST',prefer:'return=representation',body:{user_id:uid(),title:s.title,service:s.domain||'support',symptoms:[text.slice(0,500)],status:'open',journey_stage:'diagnosis',share_anonymously:false}});return rows?.[0]||null}catch(e){console.warn('Create case',e);return null}}
  async function recordEvent(type,label,details={}){if(!uid()||!session.caseRow)return;try{await api('vmusf_case_events',{method:'POST',prefer:'return=minimal',body:{case_id:session.caseRow.id,user_id:uid(),event_type:type,label,details}})}catch(e){console.warn('Case event',e)}}
  function optionButtons(q){if(!Array.isArray(q.options)||!q.options.length)return'';return `<div class="assist-choices">${q.options.map(o=>{const val=typeof o==='string'?o:(o.value??o.label??JSON.stringify(o));const lab=typeof o==='string'?o:(o.label??o.value);return `<button class="btn" type="button" data-assist-answer="${sx(val)}">${sx(lab)}</button>`}).join('')}</div>`}
  function askCurrent(){const q=session.questions[session.index];if(!q)return finishIntake();session.phase='intake';add('bot',`<b>${q.question_key==='__virgin_status'?q.prompt:sx(q.prompt)}</b>${optionButtons(q)}${q.why_it_matters?`<small>${sx(q.why_it_matters)}</small>`:''}${q.required?'':'<small>If you do not know, type “skip”.</small>'}`)}
  async function finishIntake(){if(session.phase==='conversation')return;session.phase='conversation';add('bot',`<b>That’s the important bit captured.</b><p>${uid()&&session.caseRow?`I’m keeping this under <strong>${sx(session.caseRow.case_reference||'your VMUSF case')}</strong>.`:'I’m keeping this conversation on this device for now.'}</p><p><b>You can keep talking to me.</b> Ask what to do next, tell me what Virgin said, ask about a bill, engineer, callback, complaint or compensation, or add another detail.</p>`);await recordEvent('intake_completed','Assist intake completed',{answers:session.answers});if(!uid())saveGuest()}
  async function beginScenario(s,text){session.scenario=s;session.opening=text;const normal=await questionsFor(s.scenario_key);session.questions=technical(s,text)?[...statusQuestions(),...normal]:normal;session.index=0;session.answers={};session.caseRow=await createCase(s,text);session.phase='intake';add('bot',`<b>Okay, I’ve got the right route.</b><p>${sx(s.title)}</p>${technical(s,text)?'<small>First check: is this a wider service problem?</small>':''}${session.caseRow?`<small>Case ${sx(session.caseRow.case_reference||'created')}</small>`:''}`);await recordEvent('intake_started','Assist identified scenario',{scenario_key:s.scenario_key,opening_text:text});askCurrent()}
  function saveGuest(){try{localStorage.setItem(GUEST,JSON.stringify({scenario_key:session.scenario?.scenario_key,answers:session.answers,opening:session.opening,phase:session.phase,at:new Date().toISOString()}))}catch{}}
  function scoreKnowledge(text,row){const q=words(text),hay=(String(row.heading||'')+' '+String(row.content||'')+' '+String(row.category||'')+' '+String(row.device||'')+' '+(row.keywords||[]).join(' ')).toLowerCase();let n=0;q.forEach(w=>{if(hay.includes(w))n+=w.length>6?3:1});if(session.scenario?.domain&&String(row.category||'').toLowerCase().includes(String(session.scenario.domain).toLowerCase()))n+=2;return n}
  async function knowledgeAnswer(text){const rows=await loadKnowledge();const ranked=rows.map(r=>({r,n:scoreKnowledge(text,r)})).filter(x=>x.n>1).sort((a,b)=>b.n-a.n).slice(0,2);if(!ranked.length)return null;const r=ranked[0].r,content=String(r.content||'').trim().replace(/\s+/g,' ');return `<b>${sx(r.heading||'Useful guidance')}</b><p>${sx(content.slice(0,650))}${content.length>650?'…':''}</p><small>${sx(r.authority||'Verified VMUSF knowledge')}${r.device?' · '+sx(r.device):''}</small>`}
  async function continueConversation(text){const low=text.toLowerCase();
    if(/(new|different|another) (problem|issue)|something else/.test(low)){add('bot','<p>No problem. I’ll keep this case as it is and start a fresh route for the new issue.</p>');session=fresh();return consume(text.replace(/^(i have )?(another|a different|new) (problem|issue)[: ]*/i,''));}
    if(/(resolved|fixed|working now|sorted)/.test(low)){await recordEvent('resolved_update','User says the problem is resolved',{answer:text});add('bot','<b>Good, I’ve recorded that it’s resolved.</b><p>If Virgin promised a credit, compensation or follow-up, don’t close the case until that part has actually happened.</p>');return}
    if(/(called me|rang me|phoned me|callback happened)/.test(low)){await recordEvent('provider_called','Virgin called',{answer:text});add('bot','<b>I’ve added the call to the case.</b><p>What did they agree to do, and did they give you a timescale or reference number?</p>');return}
    if(/(didn.t call|did not call|no callback|never called|missed callback)/.test(low)){await recordEvent('missed_callback','Promised callback did not happen',{answer:text});add('bot','<b>I’ve marked the callback as missed.</b><p>If they gave you a promised timescale, tell me exactly what it was, for example “within 48 hours”, and I’ll keep that with the timeline.</p>');return}
    if(/(complain|complaint|deadlock|adr|cis as|cisas|ombudsman)/.test(low)){const k=await knowledgeAnswer(text);add('bot',k||'<b>Yes, I can help organise a complaint.</b><p>Keep the date the complaint was raised, the complaint reference, what outcome you asked for, every response or missed promise, and any deadlock/ADR information. Your case timeline can be downloaded later as an evidence pack.</p>');return}
    if(/(compensation|auto compensation|credit|refund)/.test(low)){const k=await knowledgeAnswer(text);add('bot',k||'<b>I can check the compensation route, but I need the exact event.</b><p>Tell me whether this is total loss of service, a missed engineer appointment, a delayed start, billing credit, or something Virgin specifically promised.</p>');return}
    if(/(what next|what do i do|next step|now what)/.test(low)){const q=session.questions[session.index];if(q){askCurrent();return}add('bot','<b>Next, tell me what has changed since we started.</b><p>For example: Virgin called, the service came back, an engineer was booked, a promised callback was missed, or nothing has changed. I’ll use that to choose the next step.</p>');return}
    const k=await knowledgeAnswer(text);if(k){add('bot',k+`<p><small>If that doesn’t match what you meant, tell me the exact Hub/box model, error code or what Virgin told you and I’ll narrow it down.</small></p>`);await recordEvent('follow_up_question','Assist answered a follow-up',{question:text});return}
    add('bot','<b>I’m still with you.</b><p>I don’t have a confident verified answer for that exact wording yet. Give me one more detail, such as the Hub/box model, exact error message, bill charge, date, or what Virgin told you. I’ll keep it in the same case rather than making you start again.</p>');
  }
  async function consume(text){const t=text.trim();if(!t)return;
    if(!uid()&&!name()&&!session.scenario&&words(t).length<=3){localStorage.setItem('vmusf-assist-name',t.slice(0,40));add('bot',`<b>Thanks, ${sx(t.slice(0,40))}.</b><p>Now tell me what’s gone wrong.</p>`);return}
    if(session.phase==='conversation')return continueConversation(t);
    if(!session.scenario){await loadScenarios();const s=classify(t);if(!s){add('bot','<b>Which of these is closest?</b><div class="assist-choices"><button class="btn" data-assist-answer="Broadband or Wi-Fi">Broadband or Wi-Fi</button><button class="btn" data-assist-answer="TV">TV</button><button class="btn" data-assist-answer="Bill or price">Bill or price</button><button class="btn" data-assist-answer="Complaint">Complaint</button><button class="btn" data-assist-answer="Contract or leaving">Contract or leaving</button><button class="btn" data-assist-answer="Something else">Something else</button></div>');return}await beginScenario(s,t);return}
    const q=session.questions[session.index];if(!q){await finishIntake();return continueConversation(t)}
    if(/^skip$/i.test(t)&&q.required){add('bot','<p>I still need this before I can give you the right next step. If Virgin never gave it to you, just say that.</p>');return}
    if(q.question_key==='__postcode_area'){const area=window.VMUSF_STATUS_FIRST?.rememberArea?.(t)||String(t).toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,4);session.answers[q.question_key]=area;const sig=window.VMUSF_STATUS_FIRST?.communitySignal?.(area,'broadband');if(sig){add('bot',sig.count?`<p><b>I can see ${sig.count} unresolved community broadband report${sig.count===1?'':'s'} around ${sx(area)}.</b> That may be a wider issue, but it is not an official Virgin confirmation.</p>`:`<p><b>No VMUSF broadband cluster is showing around ${sx(area)} right now.</b> That still does not rule out a Virgin outage.</p>`)}await recordEvent('status_area_checked','Community outage signal checked',{postcode_area:area,community_reports:sig?.count||0});session.index++;if(!uid())saveGuest();askCurrent();return}
    if(q.question_key==='__virgin_status'){session.answers[q.question_key]=t;await recordEvent('official_status_checked','Virgin service status checked',{result:t});session.index++;if(/reports an outage/i.test(t)){add('bot','<b>That changes the route.</b><p>Don’t start resetting equipment while Virgin is reporting a wider outage. Follow the official outage update. You can keep talking to me and I’ll record what happens to your own service.</p>');session.phase='conversation';if(!uid())saveGuest();return}if(/could not check/i.test(t)){add('bot',`<p>I don’t want to guess. Use <a href="${VIRGIN_STATUS}" target="_blank" rel="noopener noreferrer">Virgin’s official service-status page</a> when you can. I’ll keep the check marked as unconfirmed.</p>`)}askCurrent();return}
    session.answers[q.question_key]=t;await recordEvent(q.creates_event_type||'answer_recorded',q.prompt,{question_key:q.question_key,answer:t,scenario_key:session.scenario.scenario_key});session.index++;if(!uid())saveGuest();askCurrent()
  }
  async function send(t){if(busy)return;busy=true;const f=document.getElementById('assist-form'),btn=f?.querySelector('[type=submit]');if(btn)btn.disabled=true;try{await consume(t)}catch(e){console.error('Assist turn failed',e);add('bot','<b>I hit a snag on that turn, but the conversation is still open.</b><p>Please send that last message again. I won’t make you restart the case.</p>')}finally{busy=false;if(btn)btn.disabled=false;document.getElementById('assist-input')?.focus({preventScroll:true})}}
  function bindAssist(){const f=document.getElementById('assist-form');if(!f||f.dataset.bound)return;f.dataset.bound='1';f.addEventListener('submit',async e=>{e.preventDefault();const i=document.getElementById('assist-input'),t=i.value.trim();if(!t)return;add('user',`<p>${sx(t)}</p>`);i.value='';await send(t)})}
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-assist-answer]');if(!b)return;e.preventDefault();const t=b.dataset.assistAnswer;add('user',`<p>${sx(t)}</p>`);send(t)},true);
  const oldRender=render;render=function(r){oldRender(r);if(r==='help')bindAssist()};
  const oldAction=action;action=function(a,d){if(a==='assist-new'){reset();return}if(a==='assist-my-cases'){if(uid())return go('account');openModal('Save your progress',`<div class="result"><h3>Want VMUSF to remember your cases?</h3><p class="lead">Create a free account to keep case history, reminders and progress across devices. You can carry on as a guest if you prefer.</p><div class="actions"><button class="btn primary" data-ma="auth-join">Create account</button><button class="btn" data-ma="auth-signin">Sign in</button></div></div>`);return}return oldAction(a,d)};
  loadScenarios();
})();