(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const hdr=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:hdr(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||('Request failed ('+r.status+')'));return d}
  const sx=v=>esc(String(v??''));
  const GUEST='vmusf-assist-guest-v2';
  let scenarios=[], session={scenario:null,questions:[],index:0,answers:{},caseRow:null,opening:''};
  const name=()=>window.VMUSF_AUTH?.user?.user_metadata?.display_name||window.VMUSF_AUTH?.user?.email?.split('@')[0]||localStorage.getItem('vmusf-assist-name')||'';

  async function loadScenarios(){if(scenarios.length)return scenarios;try{scenarios=await api('vmusf_scenarios?select=scenario_key,domain,title,description,example_utterances,trigger_terms,required_facts,workflow_key,authority_scope&active=eq.true&order=priority.desc,title.asc')||[]}catch(e){console.warn('Assist scenarios',e);scenarios=[]}return scenarios}
  function words(t){return String(t||'').toLowerCase().replace(/[^a-z0-9£. ]+/g,' ').split(/\s+/).filter(x=>x.length>2)}
  function classify(text){const w=words(text);let best=null,score=0;for(const s of scenarios){let n=0;for(const term of (s.trigger_terms||[])){const z=String(term).toLowerCase();if(text.toLowerCase().includes(z))n+=z.includes(' ')?5:3}for(const ex of (s.example_utterances||[])){const ew=words(ex);n+=ew.filter(x=>w.includes(x)).length*.6}if(n>score){score=n;best=s}}return score>=1.5?best:null}
  async function questionsFor(key){try{return await api('vmusf_scenario_questions?select=question_key,prompt,why_it_matters,answer_type,options,required,conditions,creates_event_type,creates_deadline_kind,sort_order&scenario_key=eq.'+encodeURIComponent(key)+'&active=eq.true&order=sort_order.asc')||[]}catch{return[]}}
  function bubble(role,html){return `<div class="assist-bubble ${role}">${html}</div>`}
  function greeting(){const n=name();if(uid())return bubble('bot',`<b>Welcome back${n?', '+sx(n):''}.</b><p>Tell me what has happened in your own words. I’ll work out the right journey, remember the case, and only ask what we still need.</p>`);if(n)return bubble('bot',`<b>Hi ${sx(n)}.</b><p>Tell me what is happening. You can use Assist as a guest. A free account is only needed if you want cases, evidence and reminders kept across devices.</p>`);return bubble('bot',`<b>Hi, I’m VMUSF Assist.</b><p>I can help with broadband, Wi-Fi, TV, phone, bills, complaints, contracts, privacy and more. What would you like me to call you?</p>`)}
  function helpPage(){return head('VMUSF Assist','Tell me normally.','I’ll organise the rest.','One conversation can diagnose the problem, build the case, track what Virgin promises and guide the next useful step.')+`<section class="assist-shell"><aside class="assist-rail"><b>ASSIST</b><span id="assist-case-label">${uid()?'Ready to start or resume':'Guest session'}</span><div class="assist-rail-card"><strong>How it works</strong><small>Understand → ask only what matters → confirm important facts → guide next action.</small></div><div class="assist-rail-card"><strong>Source rules</strong><small>Official policy and manufacturer guidance stay above community experience.</small></div><button class="btn" data-a="assist-my-cases">My cases</button></aside><div class="assist-main"><div id="assist-log" class="assist-log" aria-live="polite">${greeting()}</div><form id="assist-form" class="assist-compose"><label for="assist-input">Message Assist</label><textarea id="assist-input" rows="3" maxlength="2500" placeholder="e.g. My Wi-Fi keeps dropping upstairs but Ethernet is fine"></textarea><div class="actions"><button class="btn primary" type="submit">Send</button><button class="btn" type="button" data-a="assist-new">New problem</button></div><small>Never enter passwords, security answers or full payment-card details.</small></form></div></section></div>`}
  P.help=helpPage;

  function add(role,html){const l=document.getElementById('assist-log');if(!l)return;l.insertAdjacentHTML('beforeend',bubble(role,html));l.scrollTop=l.scrollHeight}
  function setCaseLabel(){const el=document.getElementById('assist-case-label');if(el)el.textContent=session.caseRow?.case_reference||session.scenario?.title||(uid()?'Ready to start or resume':'Guest session')}
  function reset(){session={scenario:null,questions:[],index:0,answers:{},caseRow:null,opening:''};if(!uid())localStorage.removeItem(GUEST);const l=document.getElementById('assist-log');if(l)l.innerHTML=greeting();setCaseLabel()}
  async function createCase(s,text){if(!uid())return null;try{const rows=await api('vmusf_support_cases',{method:'POST',prefer:'return=representation',body:{user_id:uid(),title:s.title,service:s.domain||'support',symptoms:[text.slice(0,500)],status:'open',journey_stage:'diagnosis',share_anonymously:false}});return rows?.[0]||null}catch(e){console.warn('Create case',e);return null}}
  async function recordEvent(type,label,details={}){if(!uid()||!session.caseRow)return;try{await api('vmusf_case_events',{method:'POST',prefer:'return=minimal',body:{case_id:session.caseRow.id,user_id:uid(),event_type:type,label,details}})}catch(e){console.warn('Case event',e)}}
  function optionButtons(q){if(!Array.isArray(q.options)||!q.options.length)return'';return `<div class="assist-choices">${q.options.map(o=>{const val=typeof o==='string'?o:(o.value??o.label??JSON.stringify(o));const lab=typeof o==='string'?o:(o.label??o.value);return `<button class="btn" type="button" data-assist-answer="${sx(val)}">${sx(lab)}</button>`}).join('')}</div>`}
  function askCurrent(){const q=session.questions[session.index];if(!q)return finishIntake();add('bot',`<b>${sx(q.prompt)}</b>${q.why_it_matters?`<p class="assist-why">Why I’m asking: ${sx(q.why_it_matters)}</p>`:''}${optionButtons(q)}${q.required?'':'<small>You can say “skip” if you don’t know.</small>'}`)}
  async function finishIntake(){add('bot',`<b>I’ve got enough to move this forward.</b><p>${uid()&&session.caseRow?`I’ve started <strong>${sx(session.caseRow.case_reference||'your VMUSF case')}</strong> and kept the answers with its timeline.`:'This is still a guest session, so it stays on this device unless you create an account.'}</p><p>Next I’ll use the scenario workflow, verified sources and what you’ve already told me to decide whether we should troubleshoot, gather evidence, contact Virgin, monitor a promise, or use a formal route.</p>`);if(!uid())saveGuest()}
  async function beginScenario(s,text){session.scenario=s;session.opening=text;session.questions=await questionsFor(s.scenario_key);session.index=0;session.answers={};session.caseRow=await createCase(s,text);setCaseLabel();add('bot',`<span class="assist-tag">${sx(s.domain)}</span><b>I think this is: ${sx(s.title)}</b><p>${sx(s.description||'I’ll ask a few focused questions so I don’t send you down the wrong route.')}</p>${session.caseRow?`<small>Case ${sx(session.caseRow.case_reference||'created')}</small>`:''}`);await recordEvent('intake_started','Assist identified scenario',{scenario_key:s.scenario_key,opening_text:text});askCurrent()}
  function saveGuest(){try{localStorage.setItem(GUEST,JSON.stringify({scenario_key:session.scenario?.scenario_key,answers:session.answers,opening:session.opening,at:new Date().toISOString()}))}catch{}}
  async function consume(text){const t=text.trim();if(!t)return;
    if(!uid()&&!name()&&!session.scenario&&words(t).length<=3){localStorage.setItem('vmusf-assist-name',t.slice(0,40));add('bot',`<b>Nice to meet you, ${sx(t.slice(0,40))}.</b><p>What can I help with today? Explain it normally.</p>`);return}
    if(!session.scenario){await loadScenarios();const s=classify(t);if(!s){add('bot','<b>I need one more detail before I choose a journey.</b><p>What is the main thing that is wrong: broadband/Wi-Fi, TV, phone, bill, contract, cancellation, complaint, privacy/data, account security, or something else?</p>');return}await beginScenario(s,t);return}
    const q=session.questions[session.index];if(!q){add('bot','<p>This intake is complete. Use <b>New problem</b> if this is a different issue.</p>');return}
    if(/^skip$/i.test(t)&&q.required){add('bot','<p>I do need this for the next step. If you genuinely cannot get it, tell me why, for example “Virgin didn’t give me a reference” or “I can’t find the bill”.</p>');return}
    session.answers[q.question_key]=t;await recordEvent(q.creates_event_type||'answer_recorded',q.prompt,{question_key:q.question_key,answer:t,scenario_key:session.scenario.scenario_key});session.index++;if(!uid())saveGuest();askCurrent()
  }
  function bindAssist(){const f=document.getElementById('assist-form');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const i=document.getElementById('assist-input'),t=i.value.trim();if(!t)return;add('user',`<p>${sx(t)}</p>`);i.value='';await consume(t)};document.querySelectorAll('[data-assist-answer]').forEach(b=>b.onclick=()=>{const t=b.dataset.assistAnswer;add('user',`<p>${sx(t)}</p>`);consume(t)})}
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-assist-answer]');if(!b)return;e.preventDefault();const t=b.dataset.assistAnswer;add('user',`<p>${sx(t)}</p>`);consume(t)},true);
  const oldRender=render;render=function(r){oldRender(r);if(r==='help')bindAssist()};
  const oldAction=action;action=function(a,d){if(a==='assist-new'){reset();return}if(a==='assist-my-cases'){if(uid())return go('account');openModal('Keep your cases',`<div class="result"><h3>Create a free account when you want persistence</h3><p class="lead">Guests can use Assist without signing in. An account adds multiple case references, evidence, reminders, cross-device progress and personalised return journeys.</p><div class="actions"><button class="btn primary" data-ma="auth-join">Create account</button><button class="btn" data-ma="auth-signin">Sign in</button></div></div>`);return}return oldAction(a,d)};
  loadScenarios();
})();