(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const hdr=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:hdr(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||('Request failed ('+r.status+')'));return d}
  const sx=v=>esc(String(v??''));
  const GUEST='vmusf-assist-guest-v2';
  const VIRGIN_STATUS='https://www.virginmedia.com/help/check/status';
  let scenarios=[], session={scenario:null,questions:[],index:0,answers:{},caseRow:null,opening:''};
  const name=()=>window.VMUSF_AUTH?.user?.user_metadata?.display_name||window.VMUSF_AUTH?.user?.email?.split('@')[0]||localStorage.getItem('vmusf-assist-name')||'';
  async function loadScenarios(){if(scenarios.length)return scenarios;try{scenarios=await api('vmusf_scenarios?select=scenario_key,domain,title,description,example_utterances,trigger_terms,required_facts,workflow_key,authority_scope&active=eq.true&order=priority.desc,title.asc')||[]}catch(e){console.warn('Assist scenarios',e);scenarios=[]}return scenarios}
  function words(t){return String(t||'').toLowerCase().replace(/[^a-z0-9£. ]+/g,' ').split(/\s+/).filter(x=>x.length>2)}
  function classify(text){const w=words(text);let best=null,score=0;for(const s of scenarios){let n=0;for(const term of (s.trigger_terms||[])){const z=String(term).toLowerCase();if(text.toLowerCase().includes(z))n+=z.includes(' ')?5:3}for(const ex of (s.example_utterances||[])){const ew=words(ex);n+=ew.filter(x=>w.includes(x)).length*.6}if(n>score){score=n;best=s}}return score>=1.5?best:null}
  async function questionsFor(key){try{return await api('vmusf_scenario_questions?select=question_key,prompt,why_it_matters,answer_type,options,required,conditions,creates_event_type,creates_deadline_kind,sort_order&scenario_key=eq.'+encodeURIComponent(key)+'&active=eq.true&order=sort_order.asc')||[]}catch{return[]}}
  function technical(s,text=''){const v=((s?.domain||'')+' '+(s?.scenario_key||'')+' '+text).toLowerCase();return /(broadband|wifi|wi-fi|internet|hub|tv|television|phone|landline|voice|connection|speed|disconnect|offline|outage|fault)/.test(v)}
  function statusQuestions(){return [{question_key:'__postcode_area',prompt:'Before we troubleshoot anything in your home, what is your postcode area?',why_it_matters:'I’ll use only the broad area to check whether other VMUSF members are reporting the same service problem.',required:true},{question_key:'__virgin_status',prompt:`Now check Virgin’s official service status. <a href="${VIRGIN_STATUS}" target="_blank" rel="noopener noreferrer">Open Virgin service status</a><br><br>What does Virgin show?`,options:['Virgin reports an outage','No issue shown','I could not check'],required:true}]}
  function bubble(role,html){return `<div class="assist-bubble ${role}">${html}</div>`}
  function greeting(){const n=name();if(uid())return bubble('bot',`<b>Hi${n?', '+sx(n):''}. What’s happened?</b><p>Just explain it normally. I’ll ask one thing at a time and keep the case organised for you.</p>`);if(n)return bubble('bot',`<b>Hi ${sx(n)}. What’s gone wrong?</b><p>Tell me in your own words. You can use this without an account.</p>`);return bubble('bot',`<b>Hi. What should I call you?</b><p>Then tell me what’s gone wrong with your Virgin service.</p>`)}
  function helpPage(){return head('VMUSF Assist','Tell me what happened.','','You do not need to know which section to use. Just describe the problem and I’ll guide you.')+`<section class="assist-shell"><div class="assist-main"><div id="assist-log" class="assist-log" aria-live="polite">${greeting()}</div><form id="assist-form" class="assist-compose"><label for="assist-input">Type here</label><textarea id="assist-input" rows="3" maxlength="2500" placeholder="For example: My Wi-Fi keeps dropping upstairs"></textarea><div class="actions"><button class="btn primary" type="submit">Send</button><button class="btn" type="button" data-a="assist-new">Start a different problem</button><button class="btn" type="button" data-a="assist-my-cases">My cases</button></div><small>Do not enter passwords, security answers or full payment-card details.</small></form></div></section></div>`}
  P.help=helpPage;
  function add(role,html){const l=document.getElementById('assist-log');if(!l)return;l.insertAdjacentHTML('beforeend',bubble(role,html));l.scrollTop=l.scrollHeight}
  function reset(){session={scenario:null,questions:[],index:0,answers:{},caseRow:null,opening:''};if(!uid())localStorage.removeItem(GUEST);const l=document.getElementById('assist-log');if(l)l.innerHTML=greeting()}
  async function createCase(s,text){if(!uid())return null;try{const rows=await api('vmusf_support_cases',{method:'POST',prefer:'return=representation',body:{user_id:uid(),title:s.title,service:s.domain||'support',symptoms:[text.slice(0,500)],status:'open',journey_stage:'diagnosis',share_anonymously:false}});return rows?.[0]||null}catch(e){console.warn('Create case',e);return null}}
  async function recordEvent(type,label,details={}){if(!uid()||!session.caseRow)return;try{await api('vmusf_case_events',{method:'POST',prefer:'return=minimal',body:{case_id:session.caseRow.id,user_id:uid(),event_type:type,label,details}})}catch(e){console.warn('Case event',e)}}
  function optionButtons(q){if(!Array.isArray(q.options)||!q.options.length)return'';return `<div class="assist-choices">${q.options.map(o=>{const val=typeof o==='string'?o:(o.value??o.label??JSON.stringify(o));const lab=typeof o==='string'?o:(o.label??o.value);return `<button class="btn" type="button" data-assist-answer="${sx(val)}">${sx(lab)}</button>`}).join('')}</div>`}
  function askCurrent(){const q=session.questions[session.index];if(!q)return finishIntake();add('bot',`<b>${q.question_key==='__virgin_status'?q.prompt:sx(q.prompt)}</b>${optionButtons(q)}${q.why_it_matters?`<small>${sx(q.why_it_matters)}</small>`:''}${q.required?'':'<small>If you do not know, type “skip”.</small>'}`)}
  async function finishIntake(){add('bot',`<b>Got it.</b><p>${uid()&&session.caseRow?`I’ve saved this as <strong>${sx(session.caseRow.case_reference||'your VMUSF case')}</strong>.`:'I’ve kept this on this device for now.'}</p><p>I’ll now show you the next thing to do, not a wall of options.</p>`);if(!uid())saveGuest()}
  async function beginScenario(s,text){session.scenario=s;session.opening=text;const normal=await questionsFor(s.scenario_key);session.questions=technical(s,text)?[...statusQuestions(),...normal]:normal;session.index=0;session.answers={};session.caseRow=await createCase(s,text);add('bot',`<b>Okay, I’ve got the right route.</b><p>${sx(s.title)}</p>${technical(s,text)?'<small>First check: is this a wider service problem?</small>':''}${session.caseRow?`<small>Case ${sx(session.caseRow.case_reference||'created')}</small>`:''}`);await recordEvent('intake_started','Assist identified scenario',{scenario_key:s.scenario_key,opening_text:text});askCurrent()}
  function saveGuest(){try{localStorage.setItem(GUEST,JSON.stringify({scenario_key:session.scenario?.scenario_key,answers:session.answers,opening:session.opening,at:new Date().toISOString()}))}catch{}}
  async function consume(text){const t=text.trim();if(!t)return;if(!uid()&&!name()&&!session.scenario&&words(t).length<=3){localStorage.setItem('vmusf-assist-name',t.slice(0,40));add('bot',`<b>Thanks, ${sx(t.slice(0,40))}.</b><p>Now tell me what’s gone wrong.</p>`);return}if(!session.scenario){await loadScenarios();const s=classify(t);if(!s){add('bot','<b>Which of these is closest?</b><div class="assist-choices"><button class="btn" data-assist-answer="Broadband or Wi-Fi">Broadband or Wi-Fi</button><button class="btn" data-assist-answer="TV">TV</button><button class="btn" data-assist-answer="Bill or price">Bill or price</button><button class="btn" data-assist-answer="Complaint">Complaint</button><button class="btn" data-assist-answer="Contract or leaving">Contract or leaving</button><button class="btn" data-assist-answer="Something else">Something else</button></div>');return}await beginScenario(s,t);return}const q=session.questions[session.index];if(!q){add('bot','<p>This part is done. Tap <b>Start a different problem</b> if this is something else.</p>');return}if(/^skip$/i.test(t)&&q.required){add('bot','<p>I still need this before I can give you the right next step. If Virgin never gave it to you, just say that.</p>');return}
    if(q.question_key==='__postcode_area'){const area=window.VMUSF_STATUS_FIRST?.rememberArea?.(t)||String(t).toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,4);session.answers[q.question_key]=area;const sig=window.VMUSF_STATUS_FIRST?.communitySignal?.(area,'broadband');if(sig){add('bot',sig.count?`<p><b>I can see ${sig.count} unresolved community broadband report${sig.count===1?'':'s'} around ${sx(area)}.</b> That may be a wider issue, but it is not an official Virgin confirmation.</p>`:`<p><b>No VMUSF broadband cluster is showing around ${sx(area)} right now.</b> That still does not rule out a Virgin outage.</p>`)}await recordEvent('status_area_checked','Community outage signal checked',{postcode_area:area,community_reports:sig?.count||0});session.index++;if(!uid())saveGuest();askCurrent();return}
    if(q.question_key==='__virgin_status'){session.answers[q.question_key]=t;await recordEvent('official_status_checked','Virgin service status checked',{result:t});session.index++;if(/reports an outage/i.test(t)){add('bot','<b>That changes the route.</b><p>Don’t start resetting equipment while Virgin is reporting a wider outage. Follow the official outage update. If your own service is completely lost, you can also record when it started so VMUSF can keep your personal timeline.</p><div class="assist-choices"><button class="btn" type="button" data-r="outages">Open service status</button></div>');if(!uid())saveGuest();return}if(/could not check/i.test(t)){add('bot',`<p>I don’t want to guess. Use <a href="${VIRGIN_STATUS}" target="_blank" rel="noopener noreferrer">Virgin’s official service-status page</a> when you can. I can continue, but I’ll keep the outage check marked as unconfirmed.</p>`)}askCurrent();return}
    session.answers[q.question_key]=t;await recordEvent(q.creates_event_type||'answer_recorded',q.prompt,{question_key:q.question_key,answer:t,scenario_key:session.scenario.scenario_key});session.index++;if(!uid())saveGuest();askCurrent()}
  function bindAssist(){const f=document.getElementById('assist-form');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const i=document.getElementById('assist-input'),t=i.value.trim();if(!t)return;add('user',`<p>${sx(t)}</p>`);i.value='';await consume(t)}}
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-assist-answer]');if(!b)return;e.preventDefault();const t=b.dataset.assistAnswer;add('user',`<p>${sx(t)}</p>`);consume(t)},true);
  const oldRender=render;render=function(r){oldRender(r);if(r==='help')bindAssist()};
  const oldAction=action;action=function(a,d){if(a==='assist-new'){reset();return}if(a==='assist-my-cases'){if(uid())return go('account');openModal('Save your progress',`<div class="result"><h3>Want VMUSF to remember your cases?</h3><p class="lead">Create a free account to keep case history, reminders and progress across devices. You can carry on as a guest if you prefer.</p><div class="actions"><button class="btn primary" data-ma="auth-join">Create account</button><button class="btn" data-ma="auth-signin">Sign in</button></div></div>`);return}return oldAction(a,d)};
  loadScenarios();
})();