(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const headers=()=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{})});
  async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:headers()});const t=await r.text();let d=[];if(t)try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d?.message||'Could not load VMUSF data');return d}
  const sx=v=>esc(String(v??''));
  let cases=[],snapshot=null,loading=false;
  async function load(){if(!uid()){cases=[];snapshot=null;return}if(loading)return;loading=true;try{[cases,snapshot]=await Promise.all([api('vmusf_support_cases?select=id,case_reference,title,service,status,journey_stage,next_action,next_action_at,created_at,updated_at&user_id=eq.'+encodeURIComponent(uid())+'&order=updated_at.desc&limit=30'),api('vmusf_service_snapshots?select=*&user_id=eq.'+encodeURIComponent(uid())+'&order=updated_at.desc&limit=1').then(x=>x?.[0]||null)])}catch(e){console.warn('Case centre',e)}finally{loading=false}}
  const statusLabel=s=>({open:'Open',monitoring:'Monitoring',resolved:'Resolved',closed:'Closed'}[s]||s||'Open');
  function caseCard(c){return `<button class="case-card" data-case-id="${sx(c.id)}"><div><span class="case-ref">${sx(c.case_reference||'VMUSF case')}</span><h3>${sx(c.title)}</h3><small>${sx(c.service)} · ${statusLabel(c.status)} · ${sx(String(c.journey_stage||'diagnosis').replaceAll('_',' '))}</small>${c.next_action?`<p>${sx(c.next_action)}</p>`:''}</div><span class="case-arrow">›</span></button>`}
  function accountPage(){if(!uid())return head('My VMUSF','Your help can be','personal when you sign in.','Guests can use the community and Assist. A free account adds persistent cases, reminders and cross-device progress.')+`<div class="grid"><div class="side"><h3>With an account</h3><div class="metric"><b>Multiple case references</b><small>Keep separate problems separate.</small></div><div class="metric"><b>Resume where you left off</b><small>Calls, evidence and next actions stay organised.</small></div><div class="metric"><b>Personal reminders</b><small>Callbacks, appointments and official deadlines.</small></div><div class="actions"><button class="btn primary" data-ma="auth-join">Create account</button><button class="btn" data-ma="auth-signin">Sign in</button></div></div><aside class="side"><h3>Guest privacy</h3><p class="lead" style="font-size:.95rem">Guest Assist progress remains on this device. It is not turned into somebody else’s case or community post.</p></aside></div></div>`;
    const service=snapshot?`${sx(snapshot.provider||'Virgin Media')} · ${sx(snapshot.package_name||snapshot.package||'Current service')}`:'Add your current Virgin service';
    const active=cases.filter(c=>!['resolved','closed'].includes(c.status));
    return head('My VMUSF','Your cases.','Your next useful step.','A living support workspace for your current service, active problems, reminders and completed journeys.')+`<section class="case-dashboard"><div class="case-summary"><div><small>Current service</small><b>${service}</b></div><div><small>Active cases</small><b>${active.length}</b></div><div><small>Monitoring</small><b>${cases.filter(c=>c.status==='monitoring').length}</b></div><div><small>Resolved</small><b>${cases.filter(c=>c.status==='resolved').length}</b></div></div><div class="grid"><div><div class="title"><div><h2>My cases</h2><p>Each separate issue gets its own reference and timeline.</p></div><button class="btn primary" data-r="help">Ask Assist</button></div><div id="case-list" class="case-list">${cases.length?cases.map(caseCard).join(''):'<div class="empty">No cases yet. Tell Assist what is happening and it can start one with you.</div>'}</div></div><aside class="side"><h3>Privacy & storage</h3><div class="metric"><b>Private by default</b><small>Case details are tied to your signed-in account.</small></div><div class="metric"><b>Community learning is separate</b><small>Private transcripts, account details and documents are not community knowledge.</small></div><div class="metric"><b>Close and archive</b><small>Closed cases can follow the local-archive and purge process when enabled.</small></div><button class="btn" data-a="export-data">Export my data</button></aside></div></section></div>`}
  P.account=accountPage;
  async function openCase(id){const c=cases.find(x=>x.id===id);if(!c)return;let events=[];try{events=await api('vmusf_case_events?select=event_type,label,details,worked,created_at&case_id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid())+'&order=created_at.desc&limit=50')}catch{}
    openModal(c.case_reference||'VMUSF case',`<div class="result"><span class="case-ref">${sx(c.case_reference||'Case')}</span><h3>${sx(c.title)}</h3><p class="lead">${sx(c.service)} · ${sx(statusLabel(c.status))} · ${sx(String(c.journey_stage||'diagnosis').replaceAll('_',' '))}</p>${c.next_action?`<div class="notice good"><b>Next action</b><br>${sx(c.next_action)}</div>`:''}<h3 style="margin-top:24px">Timeline</h3><div class="timeline">${events.length?events.map(e=>`<div class="event"><b>${sx(e.label)}</b><small>${new Date(e.created_at).toLocaleString('en-GB')}</small>${e.details?.answer?`<p>${sx(e.details.answer)}</p>`:''}</div>`).join(''):'<div class="empty">No timeline events yet.</div>'}</div><div class="actions"><button class="btn primary" data-case-continue="${sx(c.id)}">Continue with Assist</button></div></div>`)}
  document.addEventListener('click',e=>{const c=e.target.closest?.('[data-case-continue]');if(c){e.preventDefault();closeModal();go('help');return}const b=e.target.closest?.('[data-case-id]');if(!b)return;e.preventDefault();openCase(b.dataset.caseId)},true);
  const oldRender=render;render=function(r){oldRender(r);if(r==='account'&&uid())load().then(()=>{if(current==='account'){app.innerHTML=P.account();bind();app.focus({preventScroll:true})}})};
  window.addEventListener('vmusf-auth-changed',()=>load().then(()=>current==='account'&&render('account')));
  setTimeout(load,500);
})();