(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const h=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{}),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:h(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||'Could not save this case update');return d}
  const s=v=>esc(String(v??''));
  let cases=[];
  async function loadCases(){if(!uid()){cases=[];return}try{cases=await api('vmusf_support_cases?select=id,case_reference,title,status&user_id=eq.'+encodeURIComponent(uid())+'&status=not.in.(closed,resolved)&order=updated_at.desc&limit=30')||[]}catch{cases=[]}}
  const opts=()=>cases.map(c=>`<option value="${s(c.id)}">${s(c.case_reference)} · ${s(c.title)}</option>`).join('');
  function requireCase(title,body){if(!uid())return openModal(title,'<div class="result"><h3>Sign in first</h3><p class="lead">Calls, evidence and engineer records are private case information, so VMUSF only stores them against your signed-in account.</p><div class="actions"><button class="btn primary" data-ma="auth-signin">Sign in</button></div></div>');if(!cases.length)return openModal(title,'<div class="result"><h3>Start a case first</h3><p class="lead">Tell Assist what is happening so this record has the correct VMUSF case reference.</p><div class="actions"><button class="btn primary" onclick="closeModal();go(\'help\')">Open Assist</button></div></div>');openModal(title,body)}
  function callForm(){requireCase('Record a Virgin call',`<form id="ct-call" class="form"><div class="field"><label>Case</label><select id="ct-call-case" required>${opts()}</select></div><div class="field"><label>Call direction</label><select id="ct-call-dir"><option value="outbound">I called Virgin</option><option value="inbound">Virgin called me</option></select></div><div class="field"><label>When did the call start?</label><input id="ct-call-time" type="datetime-local" required></div><div class="field"><label>Department or team</label><input id="ct-call-dept" maxlength="120" placeholder="e.g. Retentions, faults, billing"></div><div class="field"><label>Agent name, if known</label><input id="ct-call-agent" maxlength="120"></div><div class="field"><label>Reference number, if given</label><input id="ct-call-ref" maxlength="160"></div><div class="field"><label>What was said or agreed?</label><textarea id="ct-call-notes" maxlength="6000" placeholder="Include promises, callback times, prices, engineer bookings or anything important."></textarea></div><label><input id="ct-call-rec" type="checkbox"> I have kept a recording locally on my device</label><div class="notice">VMUSF does not secretly record a phone call from this webpage. If your device lets you make a lawful recording, keep the original safely and tell VMUSF what evidence you have. A transcript must be confirmed before extracted facts become case facts.</div><button class="btn primary" type="submit">Add call to case</button></form>`)}
  function evidenceForm(){requireCase('Add case evidence',`<form id="ct-evidence" class="form"><div class="field"><label>Case</label><select id="ct-ev-case" required>${opts()}</select></div><div class="field"><label>Evidence type</label><select id="ct-ev-type"><option value="screenshot">Screenshot</option><option value="bill">Bill</option><option value="email">Email or message</option><option value="letter">Letter</option><option value="speed_test">Speed test</option><option value="reference">Reference number</option><option value="note">Written note</option><option value="recording">Call recording kept locally</option></select></div><div class="field"><label>Title</label><input id="ct-ev-title" maxlength="180" required placeholder="e.g. July bill showing £68 charge"></div><div class="field"><label>When was it captured/received?</label><input id="ct-ev-time" type="datetime-local" required></div><div class="field"><label>Important details</label><textarea id="ct-ev-value" maxlength="6000"></textarea></div><div class="notice">This step records the evidence in the case timeline. File upload/storage will be enabled separately once the private storage policy is fully wired, so keep the original PDF, screenshot, audio or letter yourself for now.</div><button class="btn primary" type="submit">Add evidence record</button></form>`)}
  function engineerForm(){requireCase('Record engineer appointment',`<form id="ct-engineer" class="form"><div class="field"><label>Case</label><select id="ct-en-case" required>${opts()}</select></div><div class="field"><label>Appointment type</label><select id="ct-en-type"><option value="engineer">Virgin engineer</option><option value="technician">Technician visit</option><option value="callback">Technical callback</option></select></div><div class="field"><label>Appointment start</label><input id="ct-en-start" type="datetime-local"></div><div class="field"><label>Appointment end/window</label><input id="ct-en-end" type="datetime-local"></div><div class="field"><label>Job/reference number</label><input id="ct-en-ref" maxlength="160"></div><div class="field"><label>What happened?</label><select id="ct-en-att"><option value="unknown">Booked / not happened yet</option><option value="yes">Engineer attended</option><option value="no">Engineer did not attend</option></select></div><div class="field"><label>Findings</label><textarea id="ct-en-find" maxlength="3000"></textarea></div><div class="field"><label>Work done / equipment replaced</label><textarea id="ct-en-work" maxlength="3000"></textarea></div><div class="field"><label>What did Virgin say happens next?</label><textarea id="ct-en-next" maxlength="2000"></textarea></div><button class="btn primary" type="submit">Save appointment</button></form>`)}
  const oldAction=action;action=function(a,d){if(a==='case-add-call')return callForm();if(a==='case-add-evidence')return evidenceForm();if(a==='case-add-engineer')return engineerForm();return oldAction(a,d)};
  modalbody.addEventListener('submit',async e=>{try{
    if(e.target.id==='ct-call'){e.preventDefault();e.stopImmediatePropagation();const caseId=document.getElementById('ct-call-case').value,notes=document.getElementById('ct-call-notes').value.trim();await api('vmusf_call_records',{method:'POST',prefer:'return=minimal',body:{case_id:caseId,user_id:uid(),started_at:new Date(document.getElementById('ct-call-time').value).toISOString(),direction:document.getElementById('ct-call-dir').value,department:document.getElementById('ct-call-dept').value.trim()||null,agent_name:document.getElementById('ct-call-agent').value.trim()||null,reference_number:document.getElementById('ct-call-ref').value.trim()||null,recording_local_only:document.getElementById('ct-call-rec').checked,transcript_text:notes||null,transcript_confirmed:!!notes,extracted_fields:{},user_confirmed_fields:{summary:notes||null}}});await api('vmusf_case_events',{method:'POST',prefer:'return=minimal',body:{case_id:caseId,user_id:uid(),event_type:'provider_call',label:'Virgin call recorded',details:{answer:notes||'Call logged',reference_number:document.getElementById('ct-call-ref').value.trim()||null}}});closeModal();toastMsg('Call added to the case.');return}
    if(e.target.id==='ct-evidence'){e.preventDefault();e.stopImmediatePropagation();const caseId=document.getElementById('ct-ev-case').value,title=document.getElementById('ct-ev-title').value.trim(),value=document.getElementById('ct-ev-value').value.trim();await api('vmusf_case_evidence',{method:'POST',prefer:'return=minimal',body:{case_id:caseId,user_id:uid(),evidence_type:document.getElementById('ct-ev-type').value,title,captured_at:new Date(document.getElementById('ct-ev-time').value).toISOString(),value_text:value||null,metadata:{storage:'user_retained_original'},private:true}});await api('vmusf_case_events',{method:'POST',prefer:'return=minimal',body:{case_id:caseId,user_id:uid(),event_type:'evidence_added',label:'Evidence added: '+title,details:{answer:value||'Evidence record added'}}});closeModal();toastMsg('Evidence added to the case.');return}
    if(e.target.id==='ct-engineer'){e.preventDefault();e.stopImmediatePropagation();const caseId=document.getElementById('ct-en-case').value,att=document.getElementById('ct-en-att').value,find=document.getElementById('ct-en-find').value.trim(),work=document.getElementById('ct-en-work').value.trim(),next=document.getElementById('ct-en-next').value.trim();await api('vmusf_case_appointments',{method:'POST',prefer:'return=minimal',body:{case_id:caseId,user_id:uid(),appointment_type:document.getElementById('ct-en-type').value,booked_at:new Date().toISOString(),appointment_start:document.getElementById('ct-en-start').value?new Date(document.getElementById('ct-en-start').value).toISOString():null,appointment_end:document.getElementById('ct-en-end').value?new Date(document.getElementById('ct-en-end').value).toISOString():null,attended:att==='unknown'?null:att==='yes',job_reference:document.getElementById('ct-en-ref').value.trim()||null,findings:find||null,work_done:work||null,next_action:next||null}});await api('vmusf_case_events',{method:'POST',prefer:'return=minimal',body:{case_id:caseId,user_id:uid(),event_type:'engineer_update',label:att==='no'?'Engineer did not attend':att==='yes'?'Engineer visit recorded':'Engineer appointment booked',details:{answer:[find,work,next].filter(Boolean).join(' · ')||'Appointment updated'}}});closeModal();toastMsg('Engineer update saved.');return}
  }catch(err){console.warn('Case tools',err);toastMsg(err.message||'Could not save that update.')}},true);
  window.VMUSF_CASE_TOOLS={refresh:loadCases};
  window.addEventListener('vmusf-auth-changed',loadCases);setTimeout(loadCases,700);
})();