(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const headers=()=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{})});
  async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:headers()});const t=await r.text();let d=[];if(t)try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d?.message||'Could not load VMUSF data');return d}
  const sx=v=>esc(String(v??''));
  let cases=[],snapshot=null,loading=false;
  async function load(){if(!uid()){cases=[];snapshot=null;return}if(loading)return;loading=true;try{[cases,snapshot]=await Promise.all([api('vmusf_support_cases?select=id,case_reference,title,service,status,journey_stage,next_action,next_action_at,created_at,updated_at&user_id=eq.'+encodeURIComponent(uid())+'&order=updated_at.desc&limit=30'),api('vmusf_service_snapshots?select=*&user_id=eq.'+encodeURIComponent(uid())+'&order=updated_at.desc&limit=1').then(x=>x?.[0]||null)])}catch(e){console.warn('Case centre',e)}finally{loading=false}}
  const statusLabel=s=>({open:'Open',monitoring:'Waiting',resolved:'Resolved',closed:'Closed'}[s]||s||'Open');
  function caseCard(c){return `<button class="case-card" data-case-id="${sx(c.id)}"><div><span class="case-ref">${sx(c.case_reference||'VMUSF case')}</span><h3>${sx(c.title)}</h3><small>${statusLabel(c.status)}</small>${c.next_action?`<p><b>Next:</b> ${sx(c.next_action)}</p>`:''}</div><span class="case-arrow">›</span></button>`}
  function accountPage(){if(!uid())return head('My VMUSF','Keep your help in one place.','','Sign in to save cases, reminders and where you got to.')+`<div class="side" style="max-width:700px;margin:auto"><h3>What an account saves</h3><p class="lead">Your open problems, what Virgin said, reminders, engineer visits and evidence notes.</p><div class="actions"><button class="btn primary" data-ma="auth-join">Create free account</button><button class="btn" data-ma="auth-signin">Sign in</button></div></div></div>`;
    const active=cases.filter(c=>!['resolved','closed'].includes(c.status));
    return head('My VMUSF','What needs your attention?','','Open a case to see the next step. Extra tools only appear inside the case when you need them.')+`<section class="case-dashboard"><div class="case-summary"><div><small>Open</small><b>${active.length}</b></div><div><small>Waiting</small><b>${cases.filter(c=>c.status==='monitoring').length}</b></div><div><small>Resolved</small><b>${cases.filter(c=>c.status==='resolved').length}</b></div></div><div class="title"><div><h2>Your cases</h2><p>${snapshot?'Virgin service saved to your account.':'Tell Assist about your first problem and it will create a case for you.'}</p></div><button class="btn primary" data-r="help">Tell Assist what happened</button></div><div id="case-list" class="case-list">${cases.length?cases.map(caseCard).join(''):'<div class="empty">Nothing to manage yet. Start with Assist and explain the problem normally.</div>'}</div></section></div>`}
  P.account=accountPage;
  async function openCase(id){const c=cases.find(x=>x.id===id);if(!c)return;let events=[];try{events=await api('vmusf_case_events?select=event_type,label,details,worked,created_at&case_id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid())+'&order=created_at.desc&limit=20')}catch{}
    openModal(c.case_reference||'Your case',`<div class="result"><span class="case-ref">${sx(c.case_reference||'Case')}</span><h3>${sx(c.title)}</h3><p class="lead">${sx(statusLabel(c.status))}</p>${c.next_action?`<div class="notice good"><b>What to do next</b><br>${sx(c.next_action)}</div>`:'<div class="notice"><b>Next step</b><br>Continue with Assist and I’ll work out what needs doing next.</div>'}<div class="actions"><button class="btn primary" data-case-continue="${sx(c.id)}">Continue this case</button><button class="btn" data-case-status="${sx(c.id)}">Dates, promises & compensation</button><button class="btn" data-case-export="${sx(c.id)}">Download case</button></div><details style="margin-top:18px"><summary><b>More case tools</b></summary><div class="actions" style="margin-top:12px"><button class="btn" data-case-tool="case-add-call">Add a call</button><button class="btn" data-case-tool="case-add-promise">Add a callback or promise</button><button class="btn" data-case-tool="case-add-evidence">Add evidence note</button><button class="btn" data-case-tool="case-add-engineer">Add engineer visit</button></div></details><details style="margin-top:14px"><summary><b>Case history</b></summary><div class="timeline" style="margin-top:12px">${events.length?events.map(e=>`<div class="event"><b>${sx(e.label)}</b><small>${new Date(e.created_at).toLocaleString('en-GB')}</small>${e.details?.answer?`<p>${sx(e.details.answer)}</p>`:''}</div>`).join(''):'<div class="empty">No history yet.</div>'}</div></details></div>`)}
  document.addEventListener('click',e=>{const tool=e.target.closest?.('[data-case-tool]');if(tool){e.preventDefault();window.VMUSF_CASE_TOOLS?.handleAction?.(tool.dataset.caseTool);return}const c=e.target.closest?.('[data-case-continue]');if(c){e.preventDefault();closeModal();go('help');return}const b=e.target.closest?.('[data-case-id]');if(!b)return;e.preventDefault();openCase(b.dataset.caseId)},true);
  const oldRender=render;render=function(r){oldRender(r);if(r==='account'&&uid())load().then(()=>{if(current==='account'){app.innerHTML=P.account();bind();app.focus({preventScroll:true});window.VMUSF_CASE_TOOLS?.refresh?.()}})};
  window.addEventListener('vmusf-auth-changed',()=>load().then(()=>current==='account'&&render('account')));
  setTimeout(load,500);
})();