(()=>{
 const uid=()=>window.VMUSF_AUTH?.user?.id||'',token=()=>window.VMUSF_AUTH?.session?.access_token||'';
 const H=()=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{})});
 async function db(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:H()}),t=await r.text();let d=[];if(t)try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d?.message||'Could not prepare your case pack');return d}
 const sx=v=>esc(String(v??''));
 const redact=s=>String(s??'').replace(/\b[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2}\b/gi,'[POSTCODE REDACTED]').replace(/\b(?:\+44\s?7\d{3}|07\d{3})\s?\d{3}\s?\d{3}\b/g,'[PHONE REDACTED]').replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[EMAIL REDACTED]');
 const fmt=d=>d?new Date(d).toLocaleString('en-GB'):'';
 const dl=(name,type,text)=>{const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 async function gather(id){const base='&case_id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid());const [c,events,calls,evidence,appointments,commitments,deadlines,entitlements]=await Promise.all([
  db('vmusf_support_cases?select=*&id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid())+'&limit=1').then(x=>x?.[0]),
  db('vmusf_case_events?select=*&case_id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid())+'&order=created_at.asc'),
  db('vmusf_call_records?select=*'+base+'&order=started_at.asc'),db('vmusf_case_evidence?select=*'+base+'&order=captured_at.asc'),db('vmusf_case_appointments?select=*'+base+'&order=appointment_start.asc'),db('vmusf_case_commitments?select=*'+base+'&order=promised_at.asc'),db('vmusf_case_deadlines?select=*'+base+'&order=due_at.asc'),db('vmusf_case_entitlements?select=*'+base+'&order=updated_at.asc')]);if(!c)throw new Error('Case not found');return {case:c,events,calls,evidence,appointments,commitments,deadlines,entitlements,generated_at:new Date().toISOString()}}
 function timeline(p){const rows=[];p.events.forEach(x=>rows.push({date:x.created_at,type:'Case update',title:x.label||x.event_type,detail:x.details?.answer||''}));p.calls.forEach(x=>rows.push({date:x.started_at,type:'Call',title:[x.direction,x.department,x.agent_name].filter(Boolean).join(' · ')||'Virgin call',detail:x.transcript_text||x.reference_number||''}));p.evidence.forEach((x,i)=>rows.push({date:x.captured_at||x.created_at,type:'Evidence',title:`E${String(i+1).padStart(2,'0')} · ${x.title||x.evidence_type}`,detail:x.value_text||''}));p.appointments.forEach(x=>rows.push({date:x.appointment_start||x.booked_at,type:'Appointment',title:x.appointment_type||'Engineer appointment',detail:[x.findings,x.work_done,x.next_action].filter(Boolean).join(' · ')}));p.commitments.forEach(x=>rows.push({date:x.promised_at,type:'Provider promise',title:x.description,detail:x.due_at?'Due '+fmt(x.due_at):''}));p.deadlines.forEach(x=>rows.push({date:x.due_at,type:'Deadline',title:x.label||x.deadline_type,detail:x.status||''}));return rows.sort((a,b)=>new Date(a.date)-new Date(b.date))}
 function printable(p,doRedact=false,kind='Full case pack'){const R=x=>doRedact?redact(x):String(x??''),rows=timeline(p),c=p.case,evidence=p.evidence||[];return `<!doctype html><html><head><meta charset="utf-8"><title>${R(c.case_reference||'VMUSF case')}</title><style>body{font:14px Arial,sans-serif;color:#111;max-width:900px;margin:32px auto;line-height:1.5}h1{font-size:28px;margin-bottom:4px}h2{margin-top:28px;border-bottom:1px solid #ddd;padding-bottom:6px}.meta{color:#555}.box{border:1px solid #ddd;border-radius:10px;padding:14px;margin:12px 0}.row{display:grid;grid-template-columns:160px 120px 1fr;gap:12px;padding:10px 0;border-bottom:1px solid #eee}.row:last-child{border:0}.evidence li{margin:7px 0}@media print{body{margin:0}.noprint{display:none}}</style></head><body><div class="noprint"><button onclick="window.print()">Print / Save as PDF</button></div><h1>${R(kind)}</h1><div class="meta">Generated locally by VMUSF on ${fmt(p.generated_at)}. This generated document is not stored by VMUSF.</div><div class="box"><b>Case:</b> ${R(c.case_reference||c.id)}<br><b>Issue:</b> ${R(c.title)}<br><b>Service:</b> ${R(c.service)}<br><b>Status:</b> ${R(c.status)}<br><b>Next action:</b> ${R(c.next_action||'')}</div><h2>Chronology</h2>${rows.map(x=>`<div class="row"><div>${R(fmt(x.date))}</div><div><b>${R(x.type)}</b></div><div><b>${R(x.title)}</b>${x.detail?`<br>${R(x.detail)}`:''}</div></div>`).join('')||'<p>No timeline entries.</p>'}<h2>Evidence index</h2><ol class="evidence">${evidence.map((x,i)=>`<li><b>E${String(i+1).padStart(2,'0')} · ${R(x.title||x.evidence_type)}</b>${x.captured_at?` · ${R(fmt(x.captured_at))}`:''}${x.value_text?`<br>${R(x.value_text)}`:''}</li>`).join('')||'<li>No evidence records added.</li>'}</ol><h2>Provider promises</h2>${p.commitments.map(x=>`<div class="box"><b>${R(x.description)}</b><br>Made: ${R(fmt(x.promised_at))}${x.due_at?`<br>Due: ${R(fmt(x.due_at))}`:''}<br>Status: ${R(x.status)}</div>`).join('')||'<p>None recorded.</p>'}<h2>Deadlines and entitlements</h2>${p.deadlines.map(x=>`<div class="box"><b>${R(x.label||x.deadline_type)}</b><br>Due: ${R(fmt(x.due_at))}<br>Status: ${R(x.status)}<br>Source type: ${R(x.source_kind)}</div>`).join('')||'<p>No tracked deadlines.</p>'}${p.entitlements.map(x=>`<div class="box"><b>${R(String(x.entitlement_key||'').replaceAll('_',' '))}</b><br>Status: ${R(x.status)}<br>${x.official_amount!=null?'Official amount: £'+Number(x.official_amount).toFixed(2):x.estimated_amount!=null?'Estimated amount: £'+Number(x.estimated_amount).toFixed(2):'Amount not calculated'}</div>`).join('')}<p class="meta">Keep original bills, letters, screenshots and recordings separately. This pack is an organised summary of information held in your VMUSF case.</p></body></html>`}
 function csv(p,doRedact=false){const R=x=>doRedact?redact(x):String(x??''),q=x=>'"'+R(x).replaceAll('"','""')+'"';return ['date,type,title,detail',...timeline(p).map(x=>[fmt(x.date),x.type,x.title,x.detail].map(q).join(','))].join('\n')}
 async function openExport(id){if(!uid())return toastMsg('Sign in to export your case.');openModal('Download case',`<div class="result"><h3>Keep your own copy</h3><p class="lead">VMUSF builds these files in your browser. The generated pack is not uploaded or stored on the server.</p><label><input type="checkbox" id="export-redact" checked> Hide likely emails, phone numbers and full postcodes in the exported copy</label><div class="actions" style="margin-top:18px"><button class="btn primary" data-export-format="print">Print / Save as PDF</button><button class="btn" data-export-format="csv">Download timeline CSV</button><button class="btn" data-export-format="json">Download full JSON backup</button></div><div class="notice">PDF uses your browser's print/save feature, so VMUSF does not need a paid PDF server.</div></div>`);modalbody.querySelectorAll('[data-export-format]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const p=await gather(id),red=document.getElementById('export-redact').checked,ref=(p.case.case_reference||'vmusf-case').replace(/[^a-z0-9_-]/gi,'_');if(b.dataset.exportFormat==='json')dl(ref+'.json','application/json',JSON.stringify(red?JSON.parse(redact(JSON.stringify(p))):p,null,2));else if(b.dataset.exportFormat==='csv')dl(ref+'-timeline.csv','text/csv;charset=utf-8',csv(p,red));else{const w=window.open('','_blank');w.document.write(printable(p,red,'VMUSF case / ADR evidence pack'));w.document.close()}}catch(e){toastMsg(e.message)}finally{b.disabled=false}})}
 document.addEventListener('click',e=>{const b=e.target.closest?.('[data-case-export]');if(!b)return;e.preventDefault();openExport(b.dataset.caseExport)},true);
 window.VMUSF_CASE_EXPORT={open:openExport};
})();