(()=>{
 const token=()=>window.VMUSF_AUTH?.session?.access_token||'',uid=()=>window.VMUSF_AUTH?.user?.id||'';
 const h=()=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{})});
 async function db(path,o={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method:o.method||'GET',headers:{...h(),...(o.prefer?{Prefer:o.prefer}:{})},body:o.body?JSON.stringify(o.body):undefined});if(!r.ok)throw new Error('Could not update this topic');const t=await r.text();return t?JSON.parse(t):null}
 function topicId(){return modalbody?.querySelector?.('[data-topic-id]')?.dataset.topicId||window.VMUSF_CURRENT_TOPIC||''}
 function inject(){if(!modalbody||!modalwrap?.classList.contains('open'))return;if(modalbody.querySelector('.vmusf-topic-tools'))return;const reply=modalbody.querySelector('form[id*=reply],textarea');if(!reply)return;const id=topicId();if(!id)return;const box=document.createElement('div');box.className='vmusf-topic-tools';box.innerHTML='<button class="btn" data-same-problem>◎ I have this too</button><button class="btn ghost" data-follow-topic>☆ Follow topic</button>';(reply.closest('form')||reply.parentElement).before(box);box.querySelector('[data-same-problem]').onclick=()=>same(id);box.querySelector('[data-follow-topic]').onclick=()=>follow(id)}
 async function follow(id){if(!uid())return toastMsg('Sign in to follow a topic.');try{await db('vmusf_topic_follows',{method:'POST',prefer:'resolution=merge-duplicates,return=minimal',body:{topic_id:id,user_id:uid()}});toastMsg('Following this topic. You’ll see its updates in notifications.')}catch(e){toastMsg(e.message)}}
 function same(id){if(!uid())return toastMsg('Sign in to add your report.');openModal('I have this problem too',`<form class="form" id="sameproblem"><input type="hidden" id="spid" value="${esc(id)}"><p class="lead">This helps VMUSF spot patterns without creating another identical topic.</p><div class="field"><label for="sparea">Broad postcode area <small>(optional)</small></label><input id="sparea" maxlength="4" placeholder="e.g. S5"><small>Never enter your full postcode.</small></div><div class="field"><label for="speq">Hub / equipment <small>(optional)</small></label><input id="speq" maxlength="60" placeholder="e.g. Hub 5"></div><button class="btn primary">Add my report</button></form>`);modalbody.querySelector('#sameproblem').onsubmit=async e=>{e.preventDefault();try{await db('vmusf_same_problem',{method:'POST',prefer:'resolution=merge-duplicates,return=minimal',body:{topic_id:spid.value,user_id:uid(),area:sparea.value.trim().toUpperCase()||null,equipment:speq.value.trim()||null}});closeModal();toastMsg('Added. VMUSF will use this to spot matching patterns.')}catch(x){toastMsg(x.message)}}}
 const mo=new MutationObserver(()=>requestAnimationFrame(inject));mo.observe(document.body,{childList:true,subtree:true});
})();