(()=>{
 const token=()=>window.VMUSF_AUTH?.session?.access_token||'',uid=()=>window.VMUSF_AUTH?.user?.id||'';
 const h=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{}),...(prefer?{Prefer:prefer}:{})});
 async function db(path,o={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method:o.method||'GET',headers:h(o.prefer||''),body:o.body===undefined?undefined:JSON.stringify(o.body)}),t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||'Could not update this topic');return d}
 const sx=s=>esc(String(s??''));
 function topicId(){return modalbody?.querySelector?.('[data-worked]')?.dataset.worked||modalbody?.querySelector?.('[data-topic-id]')?.dataset.topicId||''}
 async function inject(){if(!modalbody||!modalwrap?.classList.contains('open')||modalbody.querySelector('.vmusf-topic-tools'))return;const id=topicId();if(!id)return;const host=modalbody.querySelector('.topicopen .actions')||modalbody.querySelector('form[id*=reply]');if(!host)return;let same=[],follow=[];try{same=await db('vmusf_same_problem?select=user_id,area,equipment&topic_id=eq.'+encodeURIComponent(id));if(uid())follow=await db('vmusf_topic_follows?select=topic_id&topic_id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid()))}catch{}const mine=same.some(x=>x.user_id===uid()),following=!!follow?.length,box=document.createElement('div');box.className='vmusf-topic-tools';box.innerHTML=`<button class="btn ${mine?'':'primary'}" data-same-problem>◎ ${mine?'I have this too ✓':'I have this too'}</button><button class="btn ghost" data-follow-topic>${following?'★ Following':'☆ Follow topic'}</button>${same.length?`<span class="badge">${same.length} affected</span>`:''}<button class="btn ghost" data-call-sheet>☎ Before you call Virgin</button>`;host.append(box);box.querySelector('[data-same-problem]').onclick=()=>sameProblem(id,mine);box.querySelector('[data-follow-topic]').onclick=()=>followTopic(id,following);box.querySelector('[data-call-sheet]').onclick=()=>callSheet(id)}
 async function followTopic(id,following){if(!uid())return toastMsg('Sign in to follow a topic.');try{if(following)await db('vmusf_topic_follows?topic_id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid()),{method:'DELETE'});else await db('vmusf_topic_follows',{method:'POST',prefer:'return=minimal',body:{topic_id:id,user_id:uid()}});toastMsg(following?'Topic unfollowed.':'Following. New replies can now reach you.')}catch(e){toastMsg(e.message)}}
 async function sameProblem(id,mine){if(!uid())return toastMsg('Sign in to add your report.');if(mine){try{await db('vmusf_same_problem?topic_id=eq.'+encodeURIComponent(id)+'&user_id=eq.'+encodeURIComponent(uid()),{method:'DELETE'});toastMsg('Removed from affected members.')}catch(e){toastMsg(e.message)}return}openModal('I have this problem too',`<form class="form" id="sameproblem" data-topic="${sx(id)}"><p class="lead">This helps VMUSF spot patterns without creating another identical topic.</p><div class="field"><label for="sparea">Broad postcode area <small>(optional)</small></label><input id="sparea" maxlength="4" placeholder="e.g. S5"><small>Never enter your full postcode.</small></div><div class="field"><label for="speq">Hub / equipment <small>(optional)</small></label><input id="speq" maxlength="60" placeholder="e.g. Hub 5"></div><button class="btn primary">Add my report</button></form>`);modalbody.querySelector('#sameproblem').onsubmit=async e=>{e.preventDefault();try{await db('vmusf_same_problem',{method:'POST',prefer:'return=minimal',body:{topic_id:id,user_id:uid(),area:sparea.value.trim().toUpperCase()||null,equipment:speq.value.trim()||null}});closeModal();toastMsg('Added. This contributes to the community signal.')}catch(x){toastMsg(x.message)}}}
 async function callSheet(id){try{const [ts,rs]=await Promise.all([db('vmusf_topics?select=title,category,body,solved_reply_id&id=eq.'+encodeURIComponent(id)+'&limit=1'),db('vmusf_replies?select=id,body&topic_id=eq.'+encodeURIComponent(id)+'&order=created_at.asc&limit=30')]),t=ts?.[0];if(!t)return;const solved=rs?.find(x=>x.id===t.solved_reply_id);openModal('Before you call Virgin',`<div class="result call-sheet"><span class="tag">Call sheet</span><h3>${sx(t.title)}</h3><p>${sx(t.body)}</p>${solved?`<div class="notice good"><b>Chosen community solution</b><br>${sx(solved.body)}</div>`:''}<div class="splitline"></div><h3>Have these ready</h3><ul><li>Which service is affected and when it started</li><li>Result of the official Virgin service-status check</li><li>Your Hub / TV box model and exact lights or error code</li><li>What you have already tried</li><li>Any previous reference number or promised callback</li></ul><div class="notice warn"><b>During the call</b><br>Note the time, adviser name if offered, reference number, exactly what was promised and the timescale.</div><div class="actions"><button class="btn primary" data-r="complaints">Track the outcome</button></div></div>`)}catch(e){toastMsg(e.message)}}
 let timer;const mo=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(inject,100)});mo.observe(modalbody,{childList:true,subtree:true});
})();