(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const headers=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:headers(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=[];if(t)try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d?.message||d?.details||'Could not load complaint data');return d}
  const sx=v=>esc(String(v??''));
  let events=[],deadlines=[],cases=[];
  async function load(){if(!uid()){events=[];deadlines=[];cases=[];return}try{[events,deadlines,cases]=await Promise.all([api('vmusf_complaint_events?select=id,event_type,note,event_date,created_at&user_id=eq.'+encodeURIComponent(uid())+'&order=event_date.desc,created_at.desc&limit=100'),api('vmusf_case_deadlines?select=id,case_id,policy_key,deadline_type,label,due_at,status,source_kind,source_url,metadata&user_id=eq.'+encodeURIComponent(uid())+'&order=due_at.asc&limit=100'),api('vmusf_support_cases?select=id,case_reference,title,status,complaint_reference,journey_stage&user_id=eq.'+encodeURIComponent(uid())+'&order=updated_at.desc&limit=50')])}catch(e){console.warn('Complaints live',e)}}
  const date=v=>{try{return new Date(v).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:v?.includes?.('T')?'short':undefined})}catch{return sx(v)}};
  function complaintPage(){if(!uid())return head('Complaint tracker','Build the timeline.','Keep every promise separate.','Sign in to keep complaint references, contacts, promises, evidence and official deadlines together.')+`<div class="grid"><div class="side"><h3>Why use a case?</h3><p class="lead">A complaint is rarely one message. VMUSF keeps calls, references, engineer visits, provider promises and formal escalation checkpoints in one chronology.</p><button class="btn primary" data-ma="auth-signin">Sign in</button></div><aside class="side"><h3>You can still use Assist</h3><button class="btn" data-r="help">Open Assist</button></aside></div></div>`;
    const openCases=cases.filter(c=>!['resolved','closed'].includes(c.status));
    const ev=events.length?events.map(e=>`<div class="event"><b>${sx(String(e.event_type).replaceAll('_',' '))}</b><small>${date(e.event_date)}</small><p>${sx(e.note)}</p></div>`).join(''):'<div class="empty">No standalone complaint events yet. Events recorded through a case will still appear in that case timeline.</div>';
    const dl=deadlines.filter(d=>['pending','due'].includes(d.status)).map(d=>{const c=cases.find(x=>x.id===d.case_id);const official=d.source_kind!=='provider_promise';return `<div class="deadline-row ${official?'official-deadline':'promise-deadline'}"><div><span class="tag">${official?'OFFICIAL / POLICY':'PROVIDER PROMISE'}</span><b>${sx(d.label)}</b><small>${c?sx(c.case_reference||c.title)+' · ':''}${date(d.due_at)}</small></div><span>${sx(String(d.status).toUpperCase())}</span></div>`}).join('')||'<div class="empty">No upcoming tracked deadlines.</div>';
    return head('Complaint tracker','Evidence first.','Escalate at the right time.','Complaint contacts, Virgin promises and official eligibility clocks stay separate so the case remains accurate.')+`<section class="grid"><div><div class="title"><div><h2>Complaint timeline</h2><p>Your own notes and complaint events.</p></div><button class="btn primary" data-a="complaint-live-add">Add update</button></div><div class="timeline">${ev}</div></div><aside class="side"><h3>Current position</h3><div class="metric"><b>${openCases.length} active case${openCases.length===1?'':'s'}</b><small>${openCases.filter(c=>c.complaint_reference).length} with a complaint reference saved</small></div><button class="btn" data-r="account">Open my cases</button><hr><h3>Tracked clocks</h3><div class="deadline-list">${dl}</div></aside></section></div>`}
  P.complaints=complaintPage;
  function addForm(){openModal('Add complaint update',`<form id="complaint-live-form" class="form"><div class="field"><label>What happened?</label><select id="cl-type"><option value="complaint_submitted">Complaint submitted</option><option value="provider_response">Virgin replied</option><option value="callback">Callback/contact</option><option value="engineer">Engineer/appointment</option><option value="resolution_offer">Resolution offered</option><option value="other">Other update</option></select></div><div class="field"><label>Date</label><input id="cl-date" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>What happened?</label><textarea id="cl-note" maxlength="2000" required placeholder="Include any reference, promise or timescale they gave you."></textarea></div><button class="btn primary" type="submit">Save update</button></form>`)}
  modalbody.addEventListener('submit',async e=>{if(e.target.id!=='complaint-live-form')return;e.preventDefault();e.stopImmediatePropagation();if(!uid())return;const body={user_id:uid(),event_type:document.getElementById('cl-type').value,event_date:document.getElementById('cl-date').value,note:document.getElementById('cl-note').value.trim()};try{await api('vmusf_complaint_events',{method:'POST',prefer:'return=minimal',body});closeModal();await load();if(current==='complaints')render('complaints');toastMsg('Complaint update saved.')}catch(err){toastMsg(err.message)}},true);
  const oldAction=action;action=function(a,d){if(a==='complaint-live-add'){addForm();return}return oldAction(a,d)};
  const oldRender=render;render=function(r){oldRender(r);if(r==='complaints'&&uid())load().then(()=>{if(current==='complaints'){app.innerHTML=P.complaints();bind();app.focus({preventScroll:true})}})};
  window.addEventListener('vmusf-auth-changed',()=>load().then(()=>current==='complaints'&&render('complaints')));
  setTimeout(load,650);
})();