(() => {
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const h=()=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{})});
  async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:h()});const t=await r.text();let d=[];if(t)try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d?.message||'Could not load community pulse');return d}
  const sx=v=>esc(String(v??''));
  let topics=[],replies=[];
  async function load(){try{[topics,replies]=await Promise.all([api('vmusf_topics?select=id,title,category,body,solved_reply_id,created_at&order=created_at.desc&limit=250'),api('vmusf_replies?select=id,topic_id,created_at&order=created_at.desc&limit=2500')])}catch(e){console.warn('Forum lab',e)}}
  function sameDay(a,b=new Date()){const d=new Date(a);return d.getFullYear()===b.getFullYear()&&d.getMonth()===b.getMonth()&&d.getDate()===b.getDate()}
  function pulse(){const now=new Date(),todayPosts=topics.filter(x=>sameDay(x.created_at,now)).length,todayReplies=replies.filter(x=>sameDay(x.created_at,now)).length,unanswered=topics.filter(t=>!replies.some(r=>r.topic_id===t.id)).length,solved=topics.filter(t=>!!t.solved_reply_id).length;const cats={};topics.slice(0,40).forEach(t=>cats[t.category]=(cats[t.category]||0)+1);const hot=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Community';return `<div class="vm-spectrum" aria-hidden="true"></div><section class="vm-pulse" aria-label="Community pulse"><div class="vm-pulse-brand">Community pulse</div><div class="vm-pulse-item"><b>${todayPosts} new</b><small>topics today</small></div><div class="vm-pulse-item"><b>${todayReplies} replies</b><small>today</small></div><div class="vm-pulse-item"><b>${unanswered} waiting</b><small>for a first reply</small></div><div class="vm-pulse-item"><b>${sx(hot)}</b><small>busy category</small></div></section>`}
  function injectPulse(){const page=document.querySelector('.forum-page'),mast=page?.querySelector('.forum-mast');if(!page||!mast||page.querySelector('.vm-pulse'))return;mast.insertAdjacentHTML('afterend',pulse())}
  const words=s=>new Set(String(s||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>3));
  function score(a,b){const A=words(a),B=words(b);if(!A.size||!B.size)return 0;let n=0;A.forEach(w=>{if(B.has(w))n++});return n/Math.max(3,Math.min(A.size,B.size))}
  function matches(text){return topics.map(t=>({t,score:score(text,t.title+' '+t.body)})).filter(x=>x.score>=.22).sort((a,b)=>b.score-a.score).slice(0,3)}
  function draftKey(){const u=window.VMUSF_AUTH?.user?.id||'guest';return 'vmusf-post-draft-'+u}
  function setupPostCheck(){const form=document.getElementById('postform');if(!form||form.dataset.vmChecked)return;form.dataset.vmChecked='1';const title=form.querySelector('#pt'),body=form.querySelector('#pb'),cat=form.querySelector('#pc'),submit=form.querySelector('[type=submit]');if(!title||!body)return;const box=document.createElement('div');box.className='vm-postcheck';box.innerHTML='<div class="vm-postcheck-head"><b>Before you post</b><span class="vm-check-state">Checking as you type</span></div><div class="vm-check-list"></div><div class="vm-draft-note">Draft saved automatically on this device.</div>';submit?.before(box);const list=box.querySelector('.vm-check-list'),state=box.querySelector('.vm-check-state');try{const d=JSON.parse(localStorage.getItem(draftKey())||'null');if(d&&!title.value&&!body.value){title.value=d.title||'';body.value=d.body||'';if(cat&&d.category)cat.value=d.category;state.textContent='Draft restored'}}catch{}
    let timer;const run=()=>{clearTimeout(timer);timer=setTimeout(()=>{const text=(title.value+' '+body.value).trim();try{localStorage.setItem(draftKey(),JSON.stringify({title:title.value,body:body.value,category:cat?.value||'',savedAt:Date.now()}))}catch{}const m=text.length>12?matches(text):[];if(!m.length){list.innerHTML=text.length>20?'<div class="vm-draft-note">No obvious duplicate found. You can post when ready.</div>':'<div class="vm-draft-note">Add a little more detail and I’ll check for similar discussions.</div>';state.textContent='Looks clear';return}state.textContent='Similar discussions found';list.innerHTML='<div class="vm-draft-note">These may already contain the answer:</div>'+m.map(x=>`<button type="button" class="vm-match" data-topic="${sx(x.t.id)}"><b>${sx(x.t.title)}</b><small>${sx(x.t.category)}${x.t.solved_reply_id?' · ✓ Solved':''}</small></button>`).join('')},260)};title.addEventListener('input',run);body.addEventListener('input',run);cat?.addEventListener('change',run);form.addEventListener('submit',()=>{try{localStorage.removeItem(draftKey())}catch{}},{once:true});run()}
  function shortcuts(e){if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){const q=document.getElementById('forum-search');if(q){e.preventDefault();q.focus()}}}
  let last=0;function scroll(){const y=window.scrollY||0;if(Math.abs(y-last)<8)return;last=y;document.querySelector('.top')?.classList.toggle('vm-compact',y>44)}
  const mo=new MutationObserver(()=>{injectPulse();setupPostCheck();const q=document.getElementById('forum-search');if(q&&!q.dataset.keytip){q.dataset.keytip='1';q.placeholder='Search discussions  /'}});mo.observe(document.body,{childList:true,subtree:true});
  document.addEventListener('keydown',shortcuts);window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('vmusf-auth-changed',()=>{});
  load().then(()=>{injectPulse();setupPostCheck()});
  setInterval(()=>load().then(injectPulse),60000);
})();