(() => {
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const hdr=()=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{})});
  async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:hdr()});const t=await r.text();let d=[];if(t)try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d?.message||'Could not load the forum');return d}
  const sx=v=>esc(String(v??''));
  const ago=d=>{const n=Date.now()-new Date(d).getTime(),m=Math.max(0,Math.floor(n/60000));if(m<1)return'now';if(m<60)return m+'m';const h=Math.floor(m/60);if(h<24)return h+'h';const x=Math.floor(h/24);return x+'d'};
  let topics=[],profiles={},replies=[],confirmations=[],filter='latest',query='';
  async function load(){try{const [t,r,c]=await Promise.all([api('vmusf_topics?select=id,user_id,title,category,body,solved_reply_id,created_at&order=created_at.desc&limit=150'),api('vmusf_replies?select=id,topic_id,user_id,created_at&order=created_at.desc&limit=1500'),api('vmusf_confirmations?select=topic_id,user_id&limit=1500')]);topics=t||[];replies=r||[];confirmations=c||[];const ids=[...new Set([...topics.map(x=>x.user_id),...replies.map(x=>x.user_id)].filter(Boolean))];if(ids.length){const p=await api('vmusf_profiles?select=user_id,display_name&user_id=in.('+ids.map(encodeURIComponent).join(',')+')');profiles=Object.fromEntries((p||[]).map(x=>[x.user_id,x.display_name]))}}catch(e){console.warn('Forum first',e)}}
  const name=id=>profiles[id]||'VMUSF member';
  const replyCount=id=>replies.filter(x=>x.topic_id===id).length;
  const worked=id=>confirmations.filter(x=>x.topic_id===id).length;
  const lastActivity=t=>{const r=replies.find(x=>x.topic_id===t.id);return r?.created_at||t.created_at};
  const isFresh=t=>(Date.now()-new Date(lastActivity(t)).getTime())<60*60*1000;
  function signal(t){const rc=replyCount(t.id),wc=worked(t.id);if(t.solved_reply_id&&wc>=3)return {text:'Confirmed fix',cls:'confirmed'};if(t.solved_reply_id)return {text:'Solved',cls:'solved'};if(rc===0)return {text:'Needs reply',cls:'waiting'};if(isFresh(t))return {text:'Active now',cls:'active'};return null}
  function visible(){let a=[...topics];if(filter==='unanswered')a=a.filter(x=>replyCount(x.id)===0);if(filter==='solved')a=a.filter(x=>!!x.solved_reply_id);if(filter==='active')a.sort((x,y)=>new Date(lastActivity(y))-new Date(lastActivity(x)));if(query){const q=query.toLowerCase();a=a.filter(x=>(x.title+' '+x.body+' '+x.category).toLowerCase().includes(q))}return a}
  function row(t){const rc=replyCount(t.id),wc=worked(t.id),author=name(t.user_id),initials=author.slice(0,2).toUpperCase(),sig=signal(t);return `<button class="forum-row" data-topic="${sx(t.id)}"><span class="forum-avatar">${sx(initials)}</span><span class="forum-main"><span class="forum-titleline"><h2 class="forum-title">${sx(t.title)}</h2>${sig?`<span class="thread-signal ${sig.cls}">${sig.text}</span>`:''}</span><p class="forum-excerpt">${sx(t.body)}</p><span class="forum-meta"><span class="forum-category">${sx(t.category)}</span><span>${sx(author)}</span><span>${ago(lastActivity(t))}</span>${wc?`<span class="worked-signal">✓ ${wc} ${wc===1?'person':'people'} said it worked</span>`:''}</span></span><span class="forum-stats"><span><b>${rc}</b> repl${rc===1?'y':'ies'}</span></span></button>`}
  function categories(){const m={};topics.forEach(t=>m[t.category]=(m[t.category]||0)+1);return Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([k,n])=>`<button class="forum-cat" data-forum-cat="${sx(k)}"><span>${sx(k)}</span><span>${n}</span></button>`).join('')}
  const quick=['Broadband','Wi-Fi','TV','Billing','Contracts','Complaints','Equipment'];
  function empty(){return `<div class="forum-empty"><div class="empty-orbit" aria-hidden="true"><i></i><i></i><i></i></div><strong>${query?'Nothing found for that search.':'This bit of the forum is quiet.'}</strong><span>${query?'Try fewer words, another category, or ask the community.':'Start a conversation, or browse the most common Virgin Media topics below.'}</span><div class="empty-actions"><button class="btn primary" data-a="new-post">Start a post</button>${query?'<button class="btn" data-forum-clear>Clear search</button>':'<button class="btn" data-forum-cat="Broadband">Browse broadband</button>'}</div></div>`}
  function page(){const rows=visible(),waiting=topics.filter(t=>replyCount(t.id)===0).length,solved=topics.filter(t=>t.solved_reply_id).length;return `<div class="forum-page"><section class="forum-mast"><div><div class="forum-brandline"></div><h1>Forum</h1><p>Virgin Media help from people who use it. Ask a question, compare experiences, and keep the answer that actually worked.</p><div class="forum-pulse"><i></i><span>${topics.length} conversations · ${replies.length} replies · ${solved} solved${waiting?' · '+waiting+' waiting':''}</span></div></div><div class="forum-primary"><button class="btn primary" data-a="new-post">+ New post</button><button class="btn" data-r="help">Guided help</button></div></section><div class="forum-quick">${quick.map(x=>`<button data-forum-cat="${x}">${x}</button>`).join('')}</div><section class="forum-toolbar"><div class="forum-search"><input id="forum-search" type="search" placeholder="Search a fault, error code or bit of equipment…" value="${sx(query)}" aria-label="Search forum"></div><div class="forum-tabs" role="tablist" aria-label="Forum views"><button class="forum-tab ${filter==='latest'?'active':''}" data-forum-filter="latest">Latest</button><button class="forum-tab ${filter==='active'?'active':''}" data-forum-filter="active">Active</button><button class="forum-tab ${filter==='unanswered'?'active':''}" data-forum-filter="unanswered">Needs reply</button><button class="forum-tab ${filter==='solved'?'active':''}" data-forum-filter="solved">Solved</button></div></section><section class="forum-layout"><main><div class="forum-feed" id="forum-feed" aria-live="polite">${rows.length?rows.map(row).join(''):empty()}</div></main><aside class="forum-side"><div class="forum-sidebox community-card"><span class="eyebrow">Community</span><h3>Useful beats popular.</h3><p>VMUSF highlights solved discussions and real “worked for me” confirmations instead of chasing meaningless engagement.</p></div><div class="forum-sidebox"><h3>Browse</h3><div class="forum-cats">${categories()||quick.map(x=>`<button class="forum-cat" data-forum-cat="${x}"><span>${x}</span><span>›</span></button>`).join('')}</div></div><div class="forum-sidebox"><h3>Stuck?</h3><p>Guided help asks one thing at a time. It stays optional and never replaces the forum.</p><button class="btn" data-r="help">Get guided help</button></div></aside></section></div>`}
  P.home=page;P.community=page;
  function refreshFeed(){const f=document.getElementById('forum-feed');if(f){const rows=visible();f.innerHTML=rows.length?rows.map(row).join(''):empty();f.classList.remove('feed-swap');requestAnimationFrame(()=>f.classList.add('feed-swap'))}}
  document.addEventListener('click',e=>{const clear=e.target.closest?.('[data-forum-clear]');if(clear){query='';const i=document.getElementById('forum-search');if(i)i.value='';refreshFeed();return}const f=e.target.closest?.('[data-forum-filter]');if(f){e.preventDefault();filter=f.dataset.forumFilter;document.querySelectorAll('[data-forum-filter]').forEach(x=>x.classList.toggle('active',x.dataset.forumFilter===filter));refreshFeed();return}const c=e.target.closest?.('[data-forum-cat]');if(c){e.preventDefault();query=c.dataset.forumCat;const i=document.getElementById('forum-search');if(i)i.value=query;refreshFeed()}},true);
  document.addEventListener('input',e=>{if(e.target.id==='forum-search'){query=e.target.value.trim();refreshFeed()}},true);
  const oldRender=render;render=function(r){oldRender(r);if((r==='home'||r==='community')&&!topics.length)load().then(()=>{if(current===r){app.innerHTML=page();bind();app.focus({preventScroll:true})}})};
  load().then(()=>{if(current==='home'||current==='community')render(current)});
})();