(() => {
  const sx=v=>esc(String(v??''));
  const words=s=>new Set(String(s||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(w=>w.length>3));
  function score(a,b){const A=words(a),B=words(b);if(!A.size||!B.size)return 0;let n=0;A.forEach(w=>{if(B.has(w))n++});return n/Math.max(3,Math.min(A.size,B.size))}
  function visibleTopics(){return [...document.querySelectorAll('[data-topic]')].map(el=>({id:el.dataset.topic,title:el.querySelector('b,h2,h3')?.textContent?.trim()||'',text:el.textContent?.trim()||''})).filter(x=>x.title)}
  function draftKey(){const u=window.VMUSF_AUTH?.user?.id||'guest';return 'vmusf-post-draft-'+u}
  function setupPostCheck(){const form=document.getElementById('postform');if(!form||form.dataset.vmChecked)return;form.dataset.vmChecked='1';const title=form.querySelector('#pt'),body=form.querySelector('#pb'),cat=form.querySelector('#pc'),submit=form.querySelector('[type=submit]');if(!title||!body)return;const box=document.createElement('div');box.className='vm-postcheck';box.innerHTML='<div class="vm-postcheck-head"><b>Before you post</b><span class="vm-check-state">Ready</span></div><div class="vm-check-list"></div><div class="vm-draft-note">Draft saves on this device.</div>';submit?.before(box);const list=box.querySelector('.vm-check-list'),state=box.querySelector('.vm-check-state');try{const d=JSON.parse(localStorage.getItem(draftKey())||'null');if(d&&!title.value&&!body.value){title.value=d.title||'';body.value=d.body||'';if(cat&&d.category)cat.value=d.category;state.textContent='Draft restored'}}catch{}
    let timer;const run=()=>{clearTimeout(timer);timer=setTimeout(()=>{const text=(title.value+' '+body.value).trim();try{localStorage.setItem(draftKey(),JSON.stringify({title:title.value,body:body.value,category:cat?.value||'',savedAt:Date.now()}))}catch{}if(text.length<16){list.innerHTML='<div class="vm-draft-note">Add a little more detail and VMUSF can spot similar discussions already on this page.</div>';state.textContent='Ready';return}const m=visibleTopics().map(t=>({t,score:score(text,t.text)})).filter(x=>x.score>=.24).sort((a,b)=>b.score-a.score).slice(0,3);if(!m.length){list.innerHTML='<div class="vm-draft-note">No obvious duplicate in the discussions currently loaded.</div>';state.textContent='Looks clear';return}state.textContent='Similar discussions';list.innerHTML=m.map(x=>`<button type="button" class="vm-match" data-topic="${sx(x.t.id)}"><b>${sx(x.t.title)}</b></button>`).join('')},350)};title.addEventListener('input',run);body.addEventListener('input',run);cat?.addEventListener('change',run);form.addEventListener('submit',()=>{try{localStorage.removeItem(draftKey())}catch{}},{once:true});run()}
  function enhanceSearch(){const q=document.getElementById('forum-search');if(q&&!q.dataset.keytip){q.dataset.keytip='1';q.placeholder='Search discussions'}}
  function enhance(){setupPostCheck();enhanceSearch()}
  let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})};
  const app=document.getElementById('app');if(app)new MutationObserver(schedule).observe(app,{childList:true,subtree:true});
  document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){const q=document.getElementById('forum-search');if(q){e.preventDefault();q.focus()}}});
  let lastCompact=false;window.addEventListener('scroll',()=>{const compact=(window.scrollY||0)>48;if(compact===lastCompact)return;lastCompact=compact;document.querySelector('.top')?.classList.toggle('vm-compact',compact)},{passive:true});
  enhance();
})();