(() => {
 const sx=v=>esc(String(v??''));
 const h=()=>({apikey:SUPABASE_KEY,'Content-Type':'application/json'});
 async function api(path){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{headers:h()});const t=await r.text();let d=[];if(t)try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d?.message||'Could not load knowledge');return d}
 let sources=[],tech=[];
 async function load(){[sources,tech]=await Promise.all([
   api('vmusf_knowledge_sources?select=id,title,source_url,source_type,provider,device,category,trust_level,last_checked_at,status,authority,jurisdiction,reviewed_at&status=eq.active&order=trust_level.desc,last_checked_at.desc&limit=120'),
   api('vmusf_trusted_tech_sources?select=vendor,product_family,official_domain,support_root_url,source_priority,allow_dynamic_search,status,last_checked_at,notes&status=eq.active&order=source_priority.asc,vendor.asc')
 ]).catch(e=>{console.warn('Knowledge centre',e);return[[],[]]})}
 const age=d=>{if(!d)return'Not yet checked';const n=Math.max(0,Math.floor((Date.now()-new Date(d))/86400000));return n===0?'Checked today':n===1?'Checked yesterday':`Checked ${n} days ago`}
 const badge=s=>{const a=(s.authority||s.provider||s.source_type||'Source').toUpperCase();return `<span class="tag">${sx(a)}</span>`}
 function cards(rows){return rows.map(s=>`<article class="policy knowledge-card">${badge(s)}<h3>${sx(s.title)}</h3><p>${sx([s.category,s.device].filter(Boolean).join(' · '))}</p><small>${sx(age(s.last_checked_at||s.reviewed_at))} · Trust ${sx(s.trust_level||'—')}</small><div class="actions"><a class="btn" href="${sx(s.source_url)}" target="_blank" rel="noopener noreferrer">Open official source</a><button class="btn" data-knowledge-source="${sx(s.id)}">What does this cover?</button></div></article>`).join('')}
 function page(){const authorities=[...new Set(sources.map(s=>s.authority).filter(Boolean))];return head('Knowledge Centre','Source first.','Advice second.','VMUSF keeps official rules, provider guidance, manufacturer help and community experience visibly separate.')+`<div class="knowledge-toolbar"><input id="knowledge-q" placeholder="Search broadband, compensation, Hub 5, SAR…" aria-label="Search knowledge"><select id="knowledge-authority"><option value="">All authorities</option>${authorities.map(a=>`<option>${sx(a)}</option>`).join('')}</select></div><div class="grid"><div id="knowledge-results">${sources.length?cards(sources.slice(0,18)):'<div class="empty">Knowledge is loading…</div>'}</div><aside class="side"><h3>Source ladder</h3><div class="metric"><b>1. Law / regulator</b><small>Ofcom, ICO, legislation and applicable ADR rules.</small></div><div class="metric"><b>2. Virgin Media</b><small>Virgin-owned services, equipment and policies.</small></div><div class="metric"><b>3. Equipment maker</b><small>Official support for third-party devices.</small></div><div class="metric"><b>4. VMUSF verified</b><small>Checked interpretation and repeated outcomes.</small></div><div class="metric"><b>5. Community</b><small>Useful experience, never disguised as official.</small></div><button class="btn" data-a="trusted-tech">Trusted tech sources (${tech.length})</button></aside></div></div>`}
 P.official=page;
 function filter(){const q=(document.getElementById('knowledge-q')?.value||'').toLowerCase(),a=document.getElementById('knowledge-authority')?.value||'';const rows=sources.filter(s=>(!a||s.authority===a)&&(!q||[s.title,s.category,s.device,s.provider,s.authority].join(' ').toLowerCase().includes(q)));const host=document.getElementById('knowledge-results');if(host)host.innerHTML=rows.length?cards(rows):'<div class="empty">No matching verified source.</div>'}
 const oldRender=render;render=function(r){oldRender(r);if(r==='official'){document.getElementById('knowledge-q')?.addEventListener('input',filter);document.getElementById('knowledge-authority')?.addEventListener('change',filter)}};
 const oldAction=action;action=function(a,d){if(a==='trusted-tech'){return openModal('Trusted technical sources',`<div class="form">${tech.map(t=>`<div class="metric"><b>${sx(t.vendor)}${t.product_family?' · '+sx(t.product_family):''}</b><small>${sx(t.official_domain)} · ${sx(age(t.last_checked_at))}${t.allow_dynamic_search?' · dynamic official search allowed':''}</small></div>`).join('')}</div>`)}return oldAction(a,d)};
 document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-knowledge-source]');if(!b)return;e.preventDefault();const s=sources.find(x=>x.id===b.dataset.knowledgeSource);if(!s)return;let chunks=[];try{chunks=await api('vmusf_knowledge_chunks?select=heading,content,authority,category,device&source_id=eq.'+encodeURIComponent(s.id)+'&verified=eq.true&limit=8')}catch{}openModal(s.title,`<div class="result">${badge(s)}<p class="lead">${sx(s.category||'Verified VMUSF source')}</p>${chunks.length?chunks.map(c=>`<div class="metric"><b>${sx(c.heading||c.category||'Guidance')}</b><small>${sx(String(c.content||'').slice(0,700))}</small></div>`).join(''):'<div class="empty">The source is registered and verified, but no extracted guidance is stored yet.</div>'}<div class="actions"><a class="btn primary" href="${sx(s.source_url)}" target="_blank" rel="noopener noreferrer">Open source</a></div></div>`)},true);
 load().then(()=>{if(current==='official'){app.innerHTML=P.official();bind();document.getElementById('knowledge-q')?.addEventListener('input',filter);document.getElementById('knowledge-authority')?.addEventListener('change',filter)}})
})();