(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const h=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:h(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||d?.hint||('Request failed ('+r.status+')'));return d}
  const sx=s=>esc(String(s??''));
  const prefs={sounds:true,volume:.35,live:true,loaded:false};
  let audio=null,armed=false,lastNotificationTime=null,pollTimer=null;

  function armAudio(){armed=true;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}catch{}}
  ['pointerdown','keydown','touchstart'].forEach(ev=>window.addEventListener(ev,armAudio,{once:true,passive:true}));
  function tone(kind='notice'){
    if(!prefs.sounds||!armed)return;
    try{audio ||= new (window.AudioContext||window.webkitAudioContext)();const now=audio.currentTime,g=audio.createGain();g.connect(audio.destination);const v=Math.max(0,Math.min(1,Number(prefs.volume)||0));g.gain.setValueAtTime(0.0001,now);g.gain.exponentialRampToValueAtTime(Math.max(.0002,v*.16),now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+.42);
      const notes=kind==='solution'?[659.25,783.99]:kind==='moderation'?[392,329.63]:kind==='follow'?[523.25,659.25]:[523.25,587.33];
      notes.forEach((f,i)=>{const o=audio.createOscillator();o.type='sine';o.frequency.value=f;o.connect(g);o.start(now+i*.09);o.stop(now+.33+i*.09)});
    }catch{}
  }
  async function loadPrefs(){if(!uid()){prefs.loaded=false;return}try{const r=await api('vmusf_preferences?select=sounds_enabled,sound_volume,live_refresh&user_id=eq.'+encodeURIComponent(uid())+'&limit=1');if(r?.[0]){prefs.sounds=r[0].sounds_enabled;prefs.volume=Number(r[0].sound_volume);prefs.live=r[0].live_refresh}else await api('vmusf_preferences',{method:'POST',prefer:'return=minimal',body:{user_id:uid(),sounds_enabled:true,sound_volume:.35,live_refresh:true}});prefs.loaded=true;syncSoundUi()}catch(e){console.warn('VMUSF preferences',e)}}
  async function savePrefs(){if(!uid())return;await api('vmusf_preferences?on_conflict=user_id',{method:'POST',prefer:'resolution=merge-duplicates,return=minimal',body:{user_id:uid(),sounds_enabled:prefs.sounds,sound_volume:prefs.volume,live_refresh:prefs.live,updated_at:new Date().toISOString()}}).catch(()=>{})}

  function syncSoundUi(){const m=document.getElementById('vmusf-sounds'),l=document.getElementById('vmusf-live'),v=document.getElementById('vmusf-volume');if(m)m.textContent=prefs.sounds?'On':'Off';if(l)l.textContent=prefs.live?'On':'Off';if(v)v.value=String(Math.round(prefs.volume*100))}
  function injectAccessibility(){const a=document.getElementById('access');if(!a||document.getElementById('vmusf-sounds'))return;const wrap=document.createElement('div');wrap.innerHTML=`<div class="arow"><span>Notification sounds</span><button id="vmusf-sounds">${prefs.sounds?'On':'Off'}</button></div><div class="arow"><span>Sound volume</span><div style="display:flex;align-items:center;gap:8px"><input id="vmusf-volume" type="range" min="0" max="100" value="${Math.round(prefs.volume*100)}" aria-label="Notification sound volume" style="width:110px"><button id="vmusf-test-sound">Test</button></div></div><div class="arow"><span>Near-live updates</span><button id="vmusf-live">${prefs.live?'On':'Off'}</button></div>`;a.append(...wrap.children);document.getElementById('vmusf-sounds').onclick=()=>{prefs.sounds=!prefs.sounds;syncSoundUi();savePrefs();if(prefs.sounds)tone('notice')};document.getElementById('vmusf-test-sound').onclick=()=>{armAudio();tone('notice')};document.getElementById('vmusf-volume').oninput=e=>{prefs.volume=Number(e.target.value)/100;savePrefs()};document.getElementById('vmusf-live').onclick=()=>{prefs.live=!prefs.live;syncSoundUi();savePrefs();restartPolling()}}

  function ensureSearchButton(){let b=document.getElementById('vmusf-search');if(b)return;const links=document.querySelector('.links');if(!links)return;b=document.createElement('button');b.id='vmusf-search';b.textContent='Search';b.onclick=e=>{e.preventDefault();openSearch()};links.prepend(b)}
  async function openSearch(){openModal('Search VMUSF',`<form class="form" id="vmusf-search-form"><div class="field"><label>Search topics</label><input id="vmusf-search-q" maxlength="80" required placeholder="Wi-Fi dropping, renewal price…"></div><button class="btn primary" type="submit">Search</button></form><div id="vmusf-search-results"></div>`)}
  async function runSearch(q,offset=0){const host=document.getElementById('vmusf-search-results');if(host)host.innerHTML='<div class="empty">Searching…</div>';try{const safe=q.replace(/[%,()]/g,' ').trim();const rows=await api('vmusf_topics?select=id,title,category,body,created_at&or=(title.ilike.*'+encodeURIComponent(safe)+'*,body.ilike.*'+encodeURIComponent(safe)+'*)&order=created_at.desc&limit=15&offset='+offset);const html=(rows||[]).map(x=>`<button class="choice" data-search-topic="${sx(x.id)}"><b>${sx(x.title)}</b><small>${sx(x.category)} • ${new Date(x.created_at).toLocaleDateString('en-GB')}</small><span>${sx(x.body.slice(0,140))}${x.body.length>140?'…':''}</span></button>`).join('')||'<div class="empty">No matching topics.</div>';if(host){host.innerHTML=`<div class="form" style="margin-top:18px">${html}</div><div class="actions">${offset>0?'<button class="btn" id="vmusf-search-prev">Previous</button>':''}${(rows||[]).length===15?'<button class="btn" id="vmusf-search-next">Next</button>':''}</div>`;host.querySelectorAll('[data-search-topic]').forEach(b=>b.onclick=()=>{closeModal();go('community');setTimeout(()=>document.querySelector(`[data-topic="${CSS.escape(b.dataset.searchTopic)}"]`)?.click(),400)});host.querySelector('#vmusf-search-prev')?.addEventListener('click',()=>runSearch(q,Math.max(0,offset-15)));host.querySelector('#vmusf-search-next')?.addEventListener('click',()=>runSearch(q,offset+15))}}catch(e){if(host)host.innerHTML=`<div class="notice warn">${sx(e.message)}</div>`}}
  modalbody.addEventListener('submit',e=>{if(e.target.id==='vmusf-search-form'){e.preventDefault();e.stopImmediatePropagation();runSearch(document.getElementById('vmusf-search-q').value.trim(),0)}},true);

  async function poll(){if(!uid()||!prefs.live||document.hidden)return;try{const rows=await api('vmusf_notifications?select=id,kind,created_at,read_at&user_id=eq.'+encodeURIComponent(uid())+'&order=created_at.desc&limit=8');if(!rows?.length)return;const newest=rows[0];if(lastNotificationTime===null){lastNotificationTime=newest.created_at;return}const fresh=rows.filter(n=>new Date(n.created_at)>new Date(lastNotificationTime));if(fresh.length){lastNotificationTime=newest.created_at;const important=fresh.find(n=>n.kind==='solution')||fresh.find(n=>n.kind==='moderation')||fresh[0];tone(important.kind||'notice');document.getElementById('vmusf-bell')?.click?.bind(null);if(typeof action==='function'){try{const n=fresh.length;toastMsg(n===1?'New VMUSF notification.':`${n} new VMUSF notifications.`)}catch{}}}
      const bell=document.getElementById('vmusf-bell');if(bell){const unread=rows.filter(n=>!n.read_at).length;bell.textContent=unread?'Notifications '+unread:'Notifications';bell.setAttribute('aria-label',unread?`${unread} unread notifications`:'Notifications')}
    }catch(e){console.warn('VMUSF live poll',e)}}
  function restartPolling(){clearInterval(pollTimer);pollTimer=null;if(prefs.live)pollTimer=setInterval(poll,12000)}
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll()});window.addEventListener('focus',poll);

  const observer=new MutationObserver(()=>{injectAccessibility();ensureSearchButton();if(uid()&&!prefs.loaded){loadPrefs().then(restartPolling)}});observer.observe(document.body,{childList:true,subtree:true});
  injectAccessibility();ensureSearchButton();setTimeout(()=>{if(uid())loadPrefs().then(()=>{restartPolling();poll()})},900);
})();