(()=>{
 const KEY='vmusf_local_ai_lab';
 const MODEL='Xenova/mobilebert-uncased-mnli';
 const LIB='https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1';
 let classifier=null,loading=null,lastProgress='';
 const state=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
 const save=x=>localStorage.setItem(KEY,JSON.stringify({...state(),...x}));
 function capabilities(){const mem=Number(navigator.deviceMemory||0),cores=Number(navigator.hardwareConcurrency||0),webgpu=!!navigator.gpu,wasm=typeof WebAssembly==='object';let tier='limited';if(webgpu&&(mem>=6||!mem)&&(cores>=4||!cores))tier='good';else if(wasm&&(mem>=4||!mem))tier='basic';return{webgpu,wasm,mem,cores,tier}}
 function labels(){return[
  'broadband completely down','broadband keeps disconnecting','slow broadband speed or gaming latency','wifi coverage or weak signal','router or hub hardware fault','tv service problem','landline or digital voice fault','wrong bill or unexpected charge','refund credit or discount missing','contract renewal or cancellation problem','complaint or missed callback','automatic compensation question','engineer appointment problem','subject access request or privacy issue','account security scam or unauthorised change','moving home or switching provider','accessibility or reasonable adjustment','something else'
 ]}
 const map={
  'broadband completely down':'broadband_total_loss','broadband keeps disconnecting':'broadband_intermittent','slow broadband speed or gaming latency':'broadband_speed','wifi coverage or weak signal':'wifi_coverage','router or hub hardware fault':'hub_fault','tv service problem':'tv_no_service','landline or digital voice fault':'landline_fault','wrong bill or unexpected charge':'billing_wrong_amount','refund credit or discount missing':'billing_refund_missing','contract renewal or cancellation problem':'contract_term_dispute','complaint or missed callback':'complaint_not_logged','automatic compensation question':'auto_compensation','engineer appointment problem':'engineer_missed','subject access request or privacy issue':'sar_request','account security scam or unauthorised change':'account_takeover','moving home or switching provider':'moving_home','accessibility or reasonable adjustment':'accessibility_adjustment','something else':'other'
 };
 function setProgress(text,pct){lastProgress=text;const el=document.getElementById('localAiProgress');if(el){el.hidden=false;el.querySelector('span').textContent=text;const bar=el.querySelector('i');if(bar)bar.style.width=Math.max(3,Math.min(100,pct||3))+'%'}}
 async function loadModel(){if(classifier)return classifier;if(loading)return loading;const c=capabilities();loading=(async()=>{try{setProgress('Loading local AI runtime…',5);const {pipeline,env}=await import(LIB);env.allowLocalModels=false;env.useBrowserCache=true;const opts={device:c.webgpu?'webgpu':'wasm',dtype:c.webgpu?'q4f16':'q4',progress_callback:p=>{if(!p)return;const pct=Number(p.progress||0);const label=p.status==='progress'?'Downloading local AI model…':p.status==='ready'?'Preparing local AI…':'Loading local AI…';setProgress(label,pct)}};classifier=await pipeline('zero-shot-classification',MODEL,opts);save({installed:true,optedIn:true,model:MODEL,backend:opts.device,dtype:opts.dtype,installedAt:new Date().toISOString()});setProgress('Local AI ready on this device',100);return classifier}catch(err){console.error('Local AI load failed',err);classifier=null;save({installed:false,lastError:String(err?.message||err)});setProgress('Local AI could not start on this device',100);throw err}finally{loading=null}})();return loading}
 async function classify(text){if(!text?.trim())return null;const pipe=await loadModel();const out=await pipe(text.trim(),labels(),{multi_label:false,hypothesis_template:'This Virgin Media customer issue is about {}.'});const top=out?.labels?.[0],score=Number(out?.scores?.[0]||0);return{label:top,scenario_key:map[top]||'other',score,backend:state().backend||capabilities().webgpu?'webgpu':'wasm',raw:out}}
 async function runTest(){const input=document.getElementById('localAiPhrase'),out=document.getElementById('localAiResult');if(!input||!out)return;const t=input.value.trim();if(!t)return toastMsg('Type a phrase to test.');out.innerHTML='<b>Local AI is thinking on this device…</b>';try{const r=await classify(t);out.innerHTML=`<b>Local AI route:</b> ${esc(r.label)}<br><small>Confidence ${Math.round(r.score*100)}% · ${esc(r.scenario_key)} · runs on this device</small>`}catch(e){out.innerHTML=`<b>Could not run local AI.</b><br><small>${esc(e?.message||'This device/browser may not support the selected runtime.')}</small>`}}
 function render(){const c=capabilities(),s=state(),label=c.tier==='good'?'Good candidate':c.tier==='basic'?'May work with a small model':'Standard Assist is safer on this device',installed=!!s.installed;openModal('Local AI Lab',`<div class="result"><span class="tag">Experimental · device only</span><h3>${installed?'Local AI is installed on this device':'Install real local AI for smarter routing'}</h3><p>${installed?'The model is cached by your browser and can classify support messages locally.':'This downloads a small quantised AI model only after you press Install. It is not loaded for ordinary visitors.'}</p><div class="notice ${c.tier==='limited'?'warn':'good'}"><b>${label}</b><br>WebGPU: ${c.webgpu?'available':'not detected'} · WebAssembly: ${c.wasm?'available':'not detected'}${c.mem?` · Memory hint: ${c.mem} GB`:''}${c.cores?` · ${c.cores} logical cores`:''}</div><div id="localAiProgress" class="local-ai-progress" ${installed?'':'hidden'}><span>${installed?'Local AI ready on this device':esc(lastProgress||'Waiting')}</span><b><i style="width:${installed?100:3}%"></i></b></div><div class="actions"><button class="btn primary" id="localAiInstall">${installed?'Reload local AI':'Install local AI on this device'}</button><button class="btn ghost" id="localAiForget">Forget local AI preference</button></div><div class="splitline"></div><h3>Test the real model</h3><div class="field"><label for="localAiPhrase">Type something naturally</label><input id="localAiPhrase" maxlength="300" placeholder="e.g. They promised to call Friday and never did"></div><button class="btn" id="localAiTry">Run local AI test</button><div id="localAiResult" class="notice" style="margin-top:10px">The result will appear here.</div><div class="notice"><b>Guardrail</b><br>The model only helps understand language and choose a route. Ofcom rules, compensation, deadlines and Virgin policy still come from VMUSF’s verified sources.</div><small>Model: ${MODEL}. The model files are fetched directly by the browser and cached locally where the browser allows it.</small></div>`);
  document.getElementById('localAiInstall').onclick=async()=>{save({optedIn:true});try{await loadModel();toastMsg('Local AI is ready on this device.');render()}catch{toastMsg('Local AI could not start. Standard Assist still works.')}};
  document.getElementById('localAiTry').onclick=runTest;
  document.getElementById('localAiPhrase').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();runTest()}});
  document.getElementById('localAiForget').onclick=()=>{save({optedIn:false,installed:false});classifier=null;toastMsg('Local AI preference cleared. Browser cache may be removed later by your browser settings.');render()}
 }
 window.VMUSF_LOCAL_AI={capabilities,open:render,state,loadModel,classify,ready:()=>!!classifier};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-local-ai-lab]');if(!b)return;e.preventDefault();render()});
})();