(() => {
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const headers=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function db(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:headers(prefer),body:body===undefined?undefined:JSON.stringify(body)});const txt=await r.text();let data=null;if(txt)try{data=JSON.parse(txt)}catch{data=txt}if(!r.ok)throw new Error(data?.message||data?.details||data?.hint||('Request failed ('+r.status+')'));return data}
  const escx=s=>esc(String(s??''));
  async function staffRole(){if(!uid())return null;const r=await db('vmusf_staff?select=role,active&user_id=eq.'+encodeURIComponent(uid())+'&limit=1').catch(()=>[]);return r?.[0]?.active?r[0].role:null}
  async function ensureModerationEntry(){const role=await staffRole();const page=document.getElementById('app');if(!role||current!=='account'||!page)return;let b=page.querySelector('#moderation-entry');if(b)return;const side=page.querySelector('.side');if(!side)return;b=document.createElement('div');b.id='moderation-entry';b.innerHTML=`<div class="metric"><b>Moderation</b><small>${escx(role)} tools • review member reports</small></div><button class="btn primary" id="open-moderation">Open moderation queue</button>`;side.prepend(b);b.querySelector('#open-moderation').onclick=openQueue}
  async function openQueue(){try{const role=await staffRole();if(!role)throw new Error('Moderator access required');const reports=await db('vmusf_content_reports?select=id,reporter_id,topic_id,reply_id,reason,details,status,created_at&order=created_at.desc&limit=100');const open=reports.filter(x=>x.status==='open'),closed=reports.filter(x=>x.status!=='open');const row=x=>`<article class="policy"><div class="title" style="margin:0 0 8px"><div><span class="tag">${escx(x.status)}</span><h3>${escx(x.reason)}</h3></div><small>${new Date(x.created_at).toLocaleString('en-GB')}</small></div><p>${escx(x.details||'No extra details.')}</p><div class="actions"><button class="btn" data-mod-open="${escx(x.id)}">Review</button>${x.status==='open'?`<button class="btn ghost" data-mod-close="${escx(x.id)}">Close report</button>`:''}</div></article>`;openModal('Moderation queue',`<div class="result"><div class="metric"><b>${open.length}</b><small>Open report${open.length===1?'':'s'}</small></div><h3>Needs review</h3>${open.map(row).join('')||'<div class="empty">No open reports.</div>'}<div class="splitline"></div><h3>Reviewed / closed</h3>${closed.slice(0,25).map(row).join('')||'<div class="empty">Nothing reviewed yet.</div>'}</div>`);bindQueue(reports)}catch(e){toastMsg(e.message)}}
  function bindQueue(reports){modalbody.querySelectorAll('[data-mod-close]').forEach(b=>b.onclick=async()=>{await db('vmusf_content_reports?id=eq.'+encodeURIComponent(b.dataset.modClose),{method:'PATCH',prefer:'return=minimal',body:{status:'closed'}});openQueue();toastMsg('Report closed.')});modalbody.querySelectorAll('[data-mod-open]').forEach(b=>b.onclick=()=>reviewReport(reports.find(x=>x.id===b.dataset.modOpen))) }
  async function reviewReport(r){if(!r)return;let content=null,author=null;if(r.topic_id){const rows=await db('vmusf_topics?select=id,user_id,title,body,category,created_at&id=eq.'+encodeURIComponent(r.topic_id)+'&limit=1');content=rows?.[0];author=content?.user_id}else if(r.reply_id){const rows=await db('vmusf_replies?select=id,user_id,topic_id,body,created_at&id=eq.'+encodeURIComponent(r.reply_id)+'&limit=1');content=rows?.[0];author=content?.user_id}let profile=null;if(author){const p=await db('vmusf_profiles?select=display_name,username&user_id=eq.'+encodeURIComponent(author)+'&limit=1');profile=p?.[0]}openModal('Review report',`<div class="result"><span class="tag">${escx(r.reason)}</span><h3>${r.topic_id?'Reported topic':'Reported reply'}</h3><p class="lead">${content?escx(content.title||content.body):'This content has already been deleted.'}</p>${content?.title?`<p>${escx(content.body)}</p>`:''}<small>Author: ${escx(profile?.username?('@'+profile.username):(profile?.display_name||'VMUSF member'))}</small><div class="notice warn" style="margin-top:18px"><b>Reporter note</b><br>${escx(r.details||'No extra details.')}</div><div class="actions">${content?`<button class="btn danger" data-mod-delete="${escx(content.id)}" data-kind="${r.topic_id?'topic':'reply'}" data-report="${escx(r.id)}">Delete content</button>`:''}<button class="btn" data-mod-reviewed="${escx(r.id)}">Mark reviewed</button><button class="btn ghost" data-mod-queue>Back to queue</button></div></div>`);modalbody.querySelector('[data-mod-reviewed]')?.addEventListener('click',async()=>{await db('vmusf_content_reports?id=eq.'+encodeURIComponent(r.id),{method:'PATCH',prefer:'return=minimal',body:{status:'reviewed'}});openQueue();toastMsg('Report marked reviewed.')});modalbody.querySelector('[data-mod-queue]')?.addEventListener('click',openQueue);modalbody.querySelector('[data-mod-delete]')?.addEventListener('click',async e=>{const b=e.currentTarget,path=b.dataset.kind==='topic'?'vmusf_topics':'vmusf_replies';await db(path+'?id=eq.'+encodeURIComponent(b.dataset.modDelete),{method:'DELETE'});await db('vmusf_content_reports?id=eq.'+encodeURIComponent(b.dataset.report),{method:'PATCH',prefer:'return=minimal',body:{status:'reviewed'}});openQueue();toastMsg('Content removed and report reviewed.')})}
  const obs=new MutationObserver(()=>ensureModerationEntry());obs.observe(document.body,{subtree:true,childList:true});setTimeout(ensureModerationEntry,600);
})();