(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const hx=()=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{})});
  async function q(path,{method='GET',body}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:hx(),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||'Request failed');return d}
  const ex=s=>esc(String(s??''));
  async function viewer(){if(!uid())return;try{const rows=await q('vmusf_notifications?select=id,actor_id,kind,topic_id,reply_id,read_at,created_at&user_id=eq.'+encodeURIComponent(uid())+'&order=created_at.desc&limit=60');const ids=[...new Set((rows||[]).map(x=>x.actor_id).filter(Boolean))];let names={};if(ids.length){const ps=await q('vmusf_profiles?select=user_id,display_name,username&user_id=in.('+ids.map(encodeURIComponent).join(',')+')');(ps||[]).forEach(x=>names[x.user_id]=x.username?('@'+x.username):x.display_name)}const wording=n=>n.kind==='reply'?'replied to your topic':n.kind==='solution'?'had their reply chosen as your solution':n.kind==='confirmation'?'said your topic worked for them':n.kind==='moderation'?'sent you a moderation notice':'followed you';const list=(rows||[]).map(n=>`<button class="choice" data-vn-id="${ex(n.id)}" data-vn-topic="${ex(n.topic_id||'')}"><b>${n.kind==='moderation'?'VMUSF moderation':ex(names[n.actor_id]||'A member')} ${wording(n)}</b><small>${new Date(n.created_at).toLocaleString('en-GB')}${n.read_at?'':' • New'}</small></button>`).join('')||'<div class="empty">No notifications yet.</div>';openModal('Notifications',`<div class="form">${list}<div class="actions"><button class="btn" id="vn-all">Mark all read</button></div></div>`);document.getElementById('vn-all')?.addEventListener('click',async()=>{await q('vmusf_notifications?user_id=eq.'+encodeURIComponent(uid())+'&read_at=is.null',{method:'PATCH',body:{read_at:new Date().toISOString()}});closeModal();toastMsg('Notifications marked read.')});modalbody.querySelectorAll('[data-vn-id]').forEach(b=>b.onclick=async()=>{await q('vmusf_notifications?id=eq.'+encodeURIComponent(b.dataset.vnId),{method:'PATCH',body:{read_at:new Date().toISOString()}}).catch(()=>{});if(b.dataset.vnTopic){closeModal();go('community');setTimeout(()=>document.querySelector(`[data-topic="${CSS.escape(b.dataset.vnTopic)}"]`)?.click(),350)}})}catch(e){openModal('Notifications',`<div class="notice warn">${ex(e.message)}</div>`)}}
  const oldAction=action;action=function(a,d){if(a==='notifications')return viewer();return oldAction(a,d)};
  const mo=new MutationObserver(()=>{const b=document.getElementById('vmusf-bell');if(b&&!b.dataset.v2){b.dataset.v2='1';b.onclick=e=>{e.preventDefault();viewer()}}});mo.observe(document.body,{childList:true,subtree:true});
})();