(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const h=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:h(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||('Request failed ('+r.status+')'));return d}
  const sx=v=>esc(String(v??''));
  let reports=[],loading=false;
  const ageHours=iso=>(Date.now()-new Date(iso).getTime())/3600000;
  async function load(){if(loading)return;loading=true;try{reports=await api('outage_reports?select=id,postcode_area,service,symptoms,started_at,status,created_at,resolved_at&created_at=gte.'+encodeURIComponent(new Date(Date.now()-48*3600000).toISOString())+'&order=created_at.desc&limit=250')||[]}catch(e){console.warn('Outage radar',e);reports=[]}finally{loading=false}}
  function clusters(){const m=new Map();for(const r of reports){if(r.status==='resolved'||r.resolved_at)continue;const area=String(r.postcode_area||'Unknown').toUpperCase().replace(/\s+/g,'').slice(0,4);const service=String(r.service||'service').toLowerCase();const k=area+'|'+service;const x=m.get(k)||{area,service,count:0,last:r.created_at,symptoms:new Set()};x.count++;if(new Date(r.created_at)>new Date(x.last))x.last=r.created_at;(r.symptoms||[]).forEach(s=>x.symptoms.add(s));m.set(k,x)}return [...m.values()].sort((a,b)=>b.count-a.count||new Date(b.last)-new Date(a.last))}
  function confidence(c){if(c.count>=8)return['Strong community cluster','high'];if(c.count>=3)return['Possible community cluster','medium'];return['Single/few reports','low']}
  function page(){const cs=clusters();return head('Outage radar','Official status +','community signal.','VMUSF keeps Virgin’s official checker, nearby member reports and your own personal service incident separate so one cannot masquerade as another.')+`<div class="outage-actions"><a class="btn primary" href="https://www.virginmedia.com/help" target="_blank" rel="noopener noreferrer">Check Virgin service status</a><button class="btn" data-a="live-report-outage">Report my service problem</button><button class="btn" data-r="help">Ask Assist</button></div><div class="grid"><div><div class="title"><div><h2>Community radar</h2><p>Broad postcode area only. These are member reports, not official outage confirmations.</p></div></div><div class="stream">${cs.length?cs.map(c=>{const [label,level]=confidence(c);return `<div class="metric outage-cluster ${level}"><div class="pulsebar"><span class="dot"></span><b>${sx(c.area)} · ${sx(c.service)}</b></div><strong>${c.count} report${c.count===1?'':'s'} in the last 48 hours</strong><small>${sx(label)} · latest ${new Date(c.last).toLocaleString('en-GB')}</small>${c.symptoms.size?`<p>${sx([...c.symptoms].slice(0,4).join(' · '))}</p>`:''}</div>`}).join(''):'<div class="empty">No unresolved community reports in the last 48 hours.</div>'}</div></div><aside class="side"><h3>Three different things</h3><div class="metric"><b>Official Virgin status</b><small>Provider-owned status and diagnostics.</small></div><div class="metric"><b>Community cluster</b><small>Nearby VMUSF reports can be an early signal, but are never labelled official.</small></div><div class="metric"><b>Your incident</b><small>If your own service is completely lost, record when it started and make sure the fault is registered with Virgin. Assist can track the case and compensation checkpoints.</small></div><div class="notice"><b>Privacy</b><br>VMUSF only needs a broad postcode area for public outage clustering. Never post a full address.</div></aside></div></div>`}
  P.outages=page;
  function reportModal(){if(!uid()){openModal('Report a service problem',`<div class="result"><h3>Sign in to create a personal outage report</h3><p class="lead">You can still view community clusters as a guest. Signing in lets VMUSF keep your own incident, start time and resolution separate from the public cluster.</p><div class="actions"><button class="btn primary" data-ma="auth-join">Create account</button><button class="btn" data-ma="auth-signin">Sign in</button></div></div>`);return}openModal('Report my service problem',`<form class="form" id="live-outage-form"><div class="field"><label>Broad postcode area</label><input id="lo-area" required maxlength="4" placeholder="e.g. S5" autocomplete="postal-code"><small>Use the outward/broad area only, not your full postcode.</small></div><div class="field"><label>Service</label><select id="lo-service" required><option value="broadband">Broadband</option><option value="wifi">Wi-Fi only</option><option value="tv">TV</option><option value="phone">Home phone / Digital Voice</option><option value="multiple">More than one service</option></select></div><div class="field"><label>What is happening?</label><textarea id="lo-symptoms" required maxlength="500" placeholder="e.g. No internet on any device; Hub is online but no connection"></textarea></div><div class="field"><label>When did it start?</label><input id="lo-start" type="datetime-local" required></div><button class="btn primary" type="submit">Record incident</button></form>`)}
  async function submitReport(){const area=document.getElementById('lo-area').value.trim().toUpperCase().replace(/\s+/g,'').slice(0,4),service=document.getElementById('lo-service').value,s=document.getElementById('lo-symptoms').value.trim(),start=document.getElementById('lo-start').value;if(!area||!service||!s||!start)return;await api('outage_reports',{method:'POST',prefer:'return=minimal',body:{user_id:uid(),postcode_area:area,service,symptoms:[s],started_at:new Date(start).toISOString(),status:'open'}});closeModal();toastMsg('Your service incident has been recorded.');await load();if(current==='outages'){app.innerHTML=P.outages();bind();app.focus({preventScroll:true})}setTimeout(()=>{openModal('What next?',`<div class="result"><h3>Keep the public signal and your personal case separate</h3><p class="lead">Your report helps the community radar. If your own service is still affected, Assist can now guide the personal fault journey, including what to tell Virgin and which dates matter.</p><div class="actions"><button class="btn primary" data-r="help" id="outage-assist-go">Continue with Assist</button></div></div>`);document.getElementById('outage-assist-go')?.addEventListener('click',()=>{closeModal();go('help')})},150)}
  modalbody.addEventListener('submit',e=>{if(e.target.id!=='live-outage-form')return;e.preventDefault();e.stopImmediatePropagation();submitReport().catch(err=>toastMsg(err.message))},true);
  const oldRender=render;render=function(r){oldRender(r);if(r==='outages')load().then(()=>{if(current==='outages'){app.innerHTML=P.outages();bind();app.focus({preventScroll:true})}})};
  const oldAction=action;action=function(a,d){if(a==='live-report-outage'){reportModal();return}return oldAction(a,d)};
  load();
})();