(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const h=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:h(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||('Request failed ('+r.status+')'));return d}
  const sx=v=>esc(String(v??''));
  const VIRGIN_STATUS='https://www.virginmedia.com/help/check/status';
  const AREA_KEY='vmusf-postcode-area';
  let reports=[],loading=false;
  const cleanArea=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,4);
  const knownArea=()=>cleanArea(localStorage.getItem(AREA_KEY)||'');
  const rememberArea=v=>{const a=cleanArea(v);if(a)localStorage.setItem(AREA_KEY,a);return a};
  async function load(){if(loading)return;loading=true;try{reports=await api('outage_reports?select=id,postcode_area,service,symptoms,started_at,status,created_at,resolved_at&created_at=gte.'+encodeURIComponent(new Date(Date.now()-48*3600000).toISOString())+'&order=created_at.desc&limit=250')||[]}catch(e){console.warn('Outage radar',e);reports=[]}finally{loading=false}}
  function clusters(){const m=new Map();for(const r of reports){if(r.status==='resolved'||r.resolved_at)continue;const area=cleanArea(r.postcode_area)||'Unknown';const service=String(r.service||'service').toLowerCase();const k=area+'|'+service;const x=m.get(k)||{area,service,count:0,last:r.created_at,symptoms:new Set()};x.count++;if(new Date(r.created_at)>new Date(x.last))x.last=r.created_at;(r.symptoms||[]).forEach(s=>x.symptoms.add(s));m.set(k,x)}return [...m.values()].sort((a,b)=>b.count-a.count||new Date(b.last)-new Date(a.last))}
  function communitySignal(area,service='broadband'){const a=cleanArea(area);const matches=clusters().filter(c=>c.area===a&&(service==='multiple'||c.service===service||c.service==='multiple'));const count=matches.reduce((n,c)=>n+c.count,0);return {count,matches};}
  function confidence(c){if(c.count>=8)return['Strong community cluster','high'];if(c.count>=3)return['Possible community cluster','medium'];return['Single/few reports','low']}
  function firstCheckBlock(){const area=knownArea();if(!area)return `<section class="notice"><b>Start here if a service is not working</b><p>Enter your postcode area once. VMUSF checks nearby community reports first, then sends you straight to Virgin's official status checker.</p><button class="btn primary" data-a="status-first-check">Check my area</button></section>`;const sig=communitySignal(area);return `<section class="notice ${sig.count>=3?'warn':''}"><b>${sx(area)} status first</b><p>${sig.count?`${sig.count} unresolved community broadband report${sig.count===1?'':'s'} nearby in the last 48 hours. This is an early community signal, not Virgin confirmation.`:'No current VMUSF broadband cluster is showing for this area.'}</p><div class="actions"><button class="btn primary" data-a="status-first-check">Check again</button><a class="btn" href="${VIRGIN_STATUS}" target="_blank" rel="noopener noreferrer">Open Virgin service status</a></div></section>`}
  function page(){const cs=clusters();return head('Service status','Check the wider problem','before troubleshooting your home.','For broadband, TV or phone faults, VMUSF checks the community signal first and keeps Virgin’s official status result separate.')+`${firstCheckBlock()}<div class="outage-actions"><button class="btn primary" data-a="status-first-check">Start service check</button><button class="btn" data-a="live-report-outage">Report my service problem</button><button class="btn" data-r="help">Guided help</button></div><div class="grid"><div><div class="title"><div><h2>Community signal</h2><p>Broad postcode area only. Member reports can spot a pattern early, but they are never presented as an official Virgin outage.</p></div></div><div class="stream">${cs.length?cs.map(c=>{const [label,level]=confidence(c);return `<div class="metric outage-cluster ${level}"><div class="pulsebar"><span class="dot"></span><b>${sx(c.area)} · ${sx(c.service)}</b></div><strong>${c.count} report${c.count===1?'':'s'} in the last 48 hours</strong><small>${sx(label)} · latest ${new Date(c.last).toLocaleString('en-GB')}</small>${c.symptoms.size?`<p>${sx([...c.symptoms].slice(0,4).join(' · '))}</p>`:''}</div>`}).join(''):'<div class="empty">No unresolved community reports in the last 48 hours.</div>'}</div></div><aside class="side"><h3>The fault order</h3><div class="metric"><b>1. Wider outage?</b><small>Check VMUSF community reports and Virgin's official service status.</small></div><div class="metric"><b>2. No wider issue?</b><small>Then check the Hub, cables, Wi-Fi and individual devices.</small></div><div class="metric"><b>3. Still broken?</b><small>Register the personal fault with Virgin and let VMUSF track what happens next.</small></div><div class="notice"><b>Privacy</b><br>VMUSF stores only the broad postcode area used for community matching, not a full address.</div></aside></div></div>`}
  P.outages=page;
  function statusModal(){const area=knownArea();openModal('Check service status first',`<form id="vm-status-first" class="form"><div class="field"><label>Your postcode area</label><input id="vm-status-area" required maxlength="8" autocomplete="postal-code" value="${sx(area)}" placeholder="e.g. S5 or S57"><small>You can enter your postcode. VMUSF only keeps the broad area needed to match nearby reports.</small></div><div class="field"><label>Which service is affected?</label><select id="vm-status-service"><option value="broadband">Broadband</option><option value="wifi">Wi-Fi</option><option value="tv">TV</option><option value="phone">Home phone / Digital Voice</option><option value="multiple">More than one service</option></select></div><button class="btn primary" type="submit">Check VMUSF signal</button></form>`)}
  function showStatusResult(area,service){const sig=communitySignal(area,service);openModal('Your first check',`<div class="result"><h3>${sig.count?`VMUSF is seeing ${sig.count} nearby report${sig.count===1?'':'s'}.`:'No matching community cluster is showing right now.'}</h3><p class="lead">${sig.count?'That may point to a wider issue, but only Virgin can confirm the official service status.':'That does not rule out an outage. Virgin’s checker is still the official next step.'}</p><div class="notice"><b>Next: Virgin service status</b><br>Virgin’s status form currently asks for customer details such as name and postcode. VMUSF cannot securely fill a form on another company’s website, so you will enter those there.</div><div class="actions"><a class="btn primary" href="${VIRGIN_STATUS}" target="_blank" rel="noopener noreferrer">Open Virgin service status</a><button class="btn" data-r="help" id="status-no-outage">Virgin shows no issue</button></div><small>If Virgin confirms an outage, do not start unnecessary Hub resets. Follow the outage update and record your own loss of service if needed.</small></div>`);setTimeout(()=>document.getElementById('status-no-outage')?.addEventListener('click',()=>{closeModal();go('help')}),0)}
  function reportModal(){if(!uid()){openModal('Report a service problem',`<div class="result"><h3>Sign in to create a personal outage report</h3><p class="lead">You can still view community clusters as a guest. Signing in lets VMUSF keep your own incident, start time and resolution separate from the public cluster.</p><div class="actions"><button class="btn primary" data-ma="auth-join">Create account</button><button class="btn" data-ma="auth-signin">Sign in</button></div></div>`);return}openModal('Report my service problem',`<form class="form" id="live-outage-form"><div class="field"><label>Broad postcode area</label><input id="lo-area" required maxlength="4" placeholder="e.g. S5" autocomplete="postal-code" value="${sx(knownArea())}"><small>Use the outward/broad area only, not your full postcode.</small></div><div class="field"><label>Service</label><select id="lo-service" required><option value="broadband">Broadband</option><option value="wifi">Wi-Fi only</option><option value="tv">TV</option><option value="phone">Home phone / Digital Voice</option><option value="multiple">More than one service</option></select></div><div class="field"><label>What is happening?</label><textarea id="lo-symptoms" required maxlength="500" placeholder="e.g. No internet on any device; Hub is online but no connection"></textarea></div><div class="field"><label>When did it start?</label><input id="lo-start" type="datetime-local" required></div><button class="btn primary" type="submit">Record incident</button></form>`)}
  async function submitReport(){const area=rememberArea(document.getElementById('lo-area').value),service=document.getElementById('lo-service').value,s=document.getElementById('lo-symptoms').value.trim(),start=document.getElementById('lo-start').value;if(!area||!service||!s||!start)return;await api('outage_reports',{method:'POST',prefer:'return=minimal',body:{user_id:uid(),postcode_area:area,service,symptoms:[s],started_at:new Date(start).toISOString(),status:'open'}});closeModal();toastMsg('Your service incident has been recorded.');await load();if(current==='outages'){app.innerHTML=P.outages();bind();app.focus({preventScroll:true})}setTimeout(()=>{openModal('What next?',`<div class="result"><h3>Keep the public signal and your personal case separate</h3><p class="lead">Your report helps the community radar. If your own service is still affected, guided help can now continue the personal fault journey.</p><div class="actions"><button class="btn primary" data-r="help" id="outage-assist-go">Continue with guided help</button></div></div>`);document.getElementById('outage-assist-go')?.addEventListener('click',()=>{closeModal();go('help')})},150)}
  modalbody.addEventListener('submit',e=>{if(e.target.id==='vm-status-first'){e.preventDefault();e.stopImmediatePropagation();const area=rememberArea(document.getElementById('vm-status-area').value),service=document.getElementById('vm-status-service').value;showStatusResult(area,service);return}if(e.target.id!=='live-outage-form')return;e.preventDefault();e.stopImmediatePropagation();submitReport().catch(err=>toastMsg(err.message))},true);
  const oldRender=render;render=function(r){oldRender(r);if(r==='outages')load().then(()=>{if(current==='outages'){app.innerHTML=P.outages();bind();app.focus({preventScroll:true})}})};
  const oldAction=action;action=function(a,d){if(a==='status-first-check'){statusModal();return}if(a==='live-report-outage'){reportModal();return}return oldAction(a,d)};
  window.VMUSF_STATUS_FIRST={knownArea,rememberArea,communitySignal,statusModal,virginUrl:VIRGIN_STATUS};
  load();
})();