(() => {
  const userId=()=>window.VMUSF_AUTH?.user?.id||'';
  const accessToken=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const headers=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(accessToken()?{Authorization:'Bearer '+accessToken()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:headers(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||('Request failed '+r.status));return d}
  const s=v=>esc(String(v??''));
  let deals=[];
  let filters={minSpeed:100,maxPrice:50,tv:false,phone:false};
  async function loadDeals(){try{deals=await api('vmusf_current_public_deals?select=provider,package_name,speed_mbps,upload_speed_mbps,monthly_price,contract_months,upfront_cost,reward_value,price_schedule,price_notes,availability_note,source_url,checked_at,technology,network&order=monthly_price.asc,speed_mbps.desc')||[]}catch(e){console.warn('VMUSF deals',e);deals=[]}}
  const filtered=()=>deals.filter(d=>(!filters.minSpeed||Number(d.speed_mbps||0)>=filters.minSpeed)&&(!filters.maxPrice||Number(d.monthly_price)<=filters.maxPrice));
  function cards(){const rows=filtered();if(!rows.length)return '<div class="empty">No verified deals match those filters yet. Try lowering the speed or raising the budget.</div>';return rows.map(d=>`<article class="deal"><div><b>${s(d.provider)} · ${s(d.package_name)}</b><small>${s(d.speed_mbps||'?')} Mbps${d.upload_speed_mbps?' down · '+s(d.upload_speed_mbps)+' Mbps up':''} · ${s(d.contract_months)} months</small><small>${s(d.availability_note||'Address availability must be checked.')}</small></div><div class="price">£${Number(d.monthly_price).toFixed(2)}/mo</div><button class="btn" data-renew-deal="${s(d.provider)}|${s(d.package_name)}">Compare</button></article>`).join('')}
  function dealsPage(){return head('Renewal coach','Know your position.','Then negotiate.','Compare a real Virgin renewal offer with verified public alternatives, then use the result to prepare your next move.')+`<section class="grid"><div><div class="actions" style="margin-top:0"><button class="btn primary" data-a="renew-start">Start my renewal journey</button><button class="btn" data-a="renew-offer">I already have a Virgin offer</button></div><div class="title"><div><h2>Verified public alternatives</h2><p>Prices are only shown when VMUSF has a current trusted-source record. Availability still depends on address.</p></div></div><form id="renew-filter" class="form"><div class="field"><label>Minimum speed</label><select id="renew-speed"><option value="0">Any speed</option><option value="100" selected>100 Mbps+</option><option value="300">300 Mbps+</option><option value="500">500 Mbps+</option><option value="900">900 Mbps+</option></select></div><div class="field"><label>Maximum monthly price</label><input id="renew-max" type="number" min="1" step="1" value="50"></div><button class="btn" type="submit">Update comparison</button></form><div id="renew-results" class="stream">${cards()}</div></div><aside class="side"><h3>How VMUSF compares</h3><div class="metric"><b>Current price</b><small>What you pay now</small></div><div class="metric"><b>Renewal offer</b><small>What Virgin has actually offered you</small></div><div class="metric"><b>Public alternatives</b><small>Verified provider prices with terms and source dates</small></div><div class="metric"><b>Whole-term view</b><small>Price changes, term, upfront cost and rewards should all be considered</small></div></aside></section></div>`}
  const priorDeals=P.deals;
  P.deals=dealsPage;
  const oldRender=render;render=function(r){oldRender(r);if(r==='deals')bindRenewal()};
  function bindRenewal(){document.getElementById('renew-filter')?.addEventListener('submit',e=>{e.preventDefault();filters.minSpeed=Number(document.getElementById('renew-speed').value||0);filters.maxPrice=Number(document.getElementById('renew-max').value||0);document.getElementById('renew-results').innerHTML=cards();bindDealButtons()});bindDealButtons()}
  function bindDealButtons(){document.querySelectorAll('[data-renew-deal]').forEach(b=>b.onclick=()=>{const [provider,pkg]=b.dataset.renewDeal.split('|');const d=deals.find(x=>x.provider===provider&&x.package_name===pkg);if(!d)return;openModal(provider+' comparison',`<div class="result"><h3>${s(d.package_name)}</h3><div class="compare"><div><small>Speed</small><b>${s(d.speed_mbps||'?')} Mbps</b></div><div><small>Current public price</small><b>£${Number(d.monthly_price).toFixed(2)}/mo</b></div><div><small>Minimum term</small><b>${s(d.contract_months)} months</b></div></div><p class="lead">${s(d.price_notes||d.availability_note||'Check address availability before deciding.')}</p><div class="notice">Use this as negotiating evidence, not as proof that the deal is available at your address until the provider confirms availability.</div></div>`)} )}
  const oldAction=action;action=function(a,d){if(a==='renew-start')return renewalStart();if(a==='renew-offer')return renewalOffer();return oldAction(a,d)};
  function renewalStart(){openModal('Start renewal journey',`<form id="renew-start-form" class="form"><div class="field"><label>What are you paying Virgin now?</label><input id="rs-price" type="number" min="0" step="0.01" required></div><div class="field"><label>Current broadband speed</label><input id="rs-speed" type="number" min="1" placeholder="e.g. 500"></div><div class="field"><label>When does your contract end?</label><input id="rs-end" type="date"></div><div class="field"><label>What matters most?</label><select id="rs-priority"><option value="price">Lowest sensible price</option><option value="speed">Keep or improve speed</option><option value="simple">Simple broadband only</option><option value="bundle">Keep TV/phone bundle</option></select></div><button class="btn primary" type="submit">Build my plan</button></form>`)}
  function renewalOffer(){openModal('Add Virgin renewal offer',`<form id="renew-offer-form" class="form"><div class="field"><label>Monthly price Virgin offered</label><input id="ro-price" type="number" min="0" step="0.01" required></div><div class="field"><label>Speed offered</label><input id="ro-speed" type="number" min="1"></div><div class="field"><label>Minimum term in months</label><input id="ro-term" type="number" min="1" max="36" value="24"></div><div class="field"><label>Anything else included or promised?</label><textarea id="ro-notes" maxlength="1000"></textarea></div><button class="btn primary" type="submit">Compare this offer</button></form>`)}
  modalbody.addEventListener('submit',async e=>{if(e.target.id==='renew-start-form'){e.preventDefault();e.stopImmediatePropagation();const data={current_provider:'Virgin Media',current_monthly_price:Number(document.getElementById('rs-price').value),current_speed_mbps:Number(document.getElementById('rs-speed').value)||null,contract_end:document.getElementById('rs-end').value||null,priorities:{primary:document.getElementById('rs-priority').value},status:'comparing'};if(userId())try{await api('vmusf_renewal_sessions',{method:'POST',prefer:'return=minimal',body:{...data,user_id:userId()}})}catch(err){console.warn(err)}closeModal();go('deals');toastMsg('Renewal plan started. Add Virgin’s offer when you have it.')}if(e.target.id==='renew-offer-form'){e.preventDefault();e.stopImmediatePropagation();const p=Number(document.getElementById('ro-price').value),sp=Number(document.getElementById('ro-speed').value)||null,term=Number(document.getElementById('ro-term').value)||null,notes=document.getElementById('ro-notes').value.trim();openModal('Your negotiation position',`<div class="result"><h3>Do not accept on price alone.</h3><p class="lead">Virgin offered <b>£${p.toFixed(2)}/mo</b>${sp?' for '+sp+' Mbps':''}${term?' on a '+term+'-month term':''}.</p><p>Compare it with the verified alternatives behind this window, then decide the maximum price you would genuinely stay for.</p><div class="notice good"><b>Suggested wording:</b><br>I’m happy to stay if the overall deal is competitive. I’ve checked current alternatives and I’d like you to review the best price you can offer for the services I actually need. Please confirm the monthly price, minimum term, any scheduled price changes, and exactly what is included before I decide.</div>${notes?`<p><b>Your notes:</b> ${s(notes)}</p>`:''}</div>`)}},true);
  loadDeals().then(()=>{if(current==='deals')render('deals')});
})();