(() => {
  const userId=()=>window.VMUSF_AUTH?.user?.id||'';
  const accessToken=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const headers=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(accessToken()?{Authorization:'Bearer '+accessToken()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function api(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:headers(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||('Request failed '+r.status));return d}
  const s=v=>esc(String(v??''));
  const safeUrl=u=>{try{const x=new URL(String(u||''));return x.protocol==='https:'?x.href:''}catch{return''}};
  let deals=[];
  let filters={minSpeed:100,maxPrice:50,tv:false,phone:false};
  let activeSession=null;
  async function loadDeals(){try{deals=await api('vmusf_current_public_deals?select=provider,package_name,speed_mbps,upload_speed_mbps,tv_included,phone_included,monthly_price,contract_months,upfront_cost,reward_value,effective_monthly_price,effective_contract_cost,price_schedule,price_notes,availability_note,source_url,checked_at,technology,network,quality_status&order=effective_monthly_price.asc,speed_mbps.desc')||[]}catch(e){console.warn('VMUSF deals',e);deals=[]}}
  async function loadSession(){if(!userId()){activeSession=null;return}try{const rows=await api('vmusf_renewal_sessions?select=*&user_id=eq.'+encodeURIComponent(userId())+'&status=neq.closed&order=updated_at.desc&limit=1');activeSession=rows?.[0]||null}catch{activeSession=null}}
  const filtered=()=>deals.filter(d=>(!filters.minSpeed||Number(d.speed_mbps||0)>=filters.minSpeed)&&(!filters.maxPrice||Number(d.effective_monthly_price||d.monthly_price)<=filters.maxPrice)&&(!filters.tv||d.tv_included===true)&&(!filters.phone||d.phone_included===true));
  const money=n=>'£'+Number(n||0).toFixed(2);
  function cards(){const rows=filtered();if(!rows.length)return '<div class="empty">No verified deals match those filters yet. Try lowering the speed, raising the budget, or removing an optional service.</div>';return rows.map(d=>`<article class="deal"><div><b>${s(d.provider)} · ${s(d.package_name)}</b><small>${s(d.speed_mbps||'?')} Mbps${d.upload_speed_mbps?' down · '+s(d.upload_speed_mbps)+' Mbps up':''} · ${s(d.contract_months)} months</small><small>${d.tv_included?'TV · ':''}${d.phone_included?'Phone · ':''}${s(d.availability_note||'Address availability must be checked.')}</small></div><div class="price">${money(d.effective_monthly_price||d.monthly_price)}/mo</div><button class="btn" data-renew-deal="${s(d.provider)}|${s(d.package_name)}">Compare</button></article>`).join('')}
  function sessionBanner(){if(!activeSession)return'';return `<div class="notice good"><b>Renewal journey in progress</b><br>Current price: ${money(activeSession.current_monthly_price)}${activeSession.current_speed_mbps?' · '+s(activeSession.current_speed_mbps)+' Mbps':''}${activeSession.contract_end?' · contract ends '+new Date(activeSession.contract_end+'T12:00:00').toLocaleDateString('en-GB'):''}. <button class="btn ghost" data-a="renew-offer">Add/update Virgin offer</button></div>`}
  function dealsPage(){return head('Renewal coach','Know your position.','Then negotiate.','Compare a real Virgin renewal offer with verified public alternatives, then use the result to prepare your next move.')+`<section class="grid"><div>${sessionBanner()}<div class="notice"><b>Independent comparison:</b> VMUSF does not sell broadband or switch you. If you choose another provider, we send you to that provider’s own website to check your address and continue directly with them.</div><div class="actions"><button class="btn primary" data-a="renew-start">${activeSession?'Update my renewal plan':'Start my renewal journey'}</button><button class="btn" data-a="renew-offer">I have a Virgin offer</button></div><div class="title"><div><h2>Verified public alternatives</h2><p>Only quality-checked records appear here. Availability and the final price must still be confirmed by the provider.</p></div></div><form id="renew-filter" class="form"><div class="field"><label>Minimum speed</label><select id="renew-speed"><option value="0">Any speed</option><option value="100" ${filters.minSpeed===100?'selected':''}>100 Mbps+</option><option value="300" ${filters.minSpeed===300?'selected':''}>300 Mbps+</option><option value="500" ${filters.minSpeed===500?'selected':''}>500 Mbps+</option><option value="900" ${filters.minSpeed===900?'selected':''}>900 Mbps+</option></select></div><div class="field"><label>Maximum effective monthly price</label><input id="renew-max" type="number" min="1" step="1" value="${s(filters.maxPrice)}"></div><label><input id="renew-tv" type="checkbox" ${filters.tv?'checked':''}> Must include TV</label><label><input id="renew-phone" type="checkbox" ${filters.phone?'checked':''}> Must include phone</label><button class="btn" type="submit">Update comparison</button></form><div id="renew-results" class="stream">${cards()}</div></div><aside class="side"><h3>How VMUSF compares</h3><div class="metric"><b>Current price</b><small>What you actually pay now</small></div><div class="metric"><b>Virgin renewal offer</b><small>What Virgin has actually offered, including term and extras</small></div><div class="metric"><b>Public alternatives</b><small>Verified public prices, not an in-site sale</small></div><div class="metric"><b>Whole-term view</b><small>Scheduled increases, upfront costs and rewards are included where verified</small></div></aside></section></div>`}
  P.deals=dealsPage;
  const oldRender=render;render=function(r){oldRender(r);if(r==='deals')bindRenewal()};
  function bindRenewal(){document.getElementById('renew-filter')?.addEventListener('submit',e=>{e.preventDefault();filters.minSpeed=Number(document.getElementById('renew-speed').value||0);filters.maxPrice=Number(document.getElementById('renew-max').value||0);filters.tv=document.getElementById('renew-tv').checked;filters.phone=document.getElementById('renew-phone').checked;document.getElementById('renew-results').innerHTML=cards();bindDealButtons()});bindDealButtons()}
  function bindDealButtons(){document.querySelectorAll('[data-renew-deal]').forEach(b=>b.onclick=()=>{const [provider,pkg]=b.dataset.renewDeal.split('|');const d=deals.find(x=>x.provider===provider&&x.package_name===pkg);if(!d)return;const u=safeUrl(d.source_url);openModal(provider+' comparison',`<div class="result"><h3>${s(d.package_name)}</h3><div class="compare"><div><small>Speed</small><b>${s(d.speed_mbps||'?')} Mbps</b></div><div><small>Headline price</small><b>${money(d.monthly_price)}/mo</b></div><div><small>Effective monthly</small><b>${money(d.effective_monthly_price||d.monthly_price)}/mo</b></div><div><small>Minimum term</small><b>${s(d.contract_months)} months</b></div></div><p class="lead">${s(d.price_notes||d.availability_note||'Check address availability before deciding.')}</p><div class="notice">VMUSF is showing comparison information only. The provider must confirm availability, eligibility, final price and contract terms at your address.</div>${u?`<div class="actions"><a class="btn primary" href="${s(u)}" target="_blank" rel="noopener noreferrer">Check availability on ${s(d.provider)}</a></div>`:'<div class="notice warn">The official provider link for this record is being re-verified. VMUSF will not send you to an unverified destination.</div>'}</div>`)} )}
  const oldAction=action;action=function(a,d){if(a==='renew-start')return renewalStart();if(a==='renew-offer')return renewalOffer();return oldAction(a,d)};
  function renewalStart(){const p=state.profile||{};const inferredSpeed=Number(String(p.package||'').match(/\d+/)?.[0]||'');openModal('Start renewal journey',`<form id="renew-start-form" class="form"><div class="field"><label>What are you paying Virgin now?</label><input id="rs-price" type="number" min="0" step="0.01" required value="${activeSession?.current_monthly_price??Number(p.price||0)}"></div><div class="field"><label>Current broadband speed</label><input id="rs-speed" type="number" min="1" placeholder="e.g. 500" value="${activeSession?.current_speed_mbps??inferredSpeed||''}"></div><div class="field"><label>When does your contract end?</label><input id="rs-end" type="date" value="${s(activeSession?.contract_end||p.contractEnd||'')}"></div><div class="field"><label>What matters most?</label><select id="rs-priority"><option value="price">Lowest sensible price</option><option value="speed">Keep or improve speed</option><option value="simple">Simple broadband only</option><option value="bundle">Keep TV/phone bundle</option></select></div><div class="field"><label>Maximum monthly price you would happily stay for</label><input id="rs-target" type="number" min="0" step="0.01" value="${activeSession?.target_monthly_price??''}"></div><button class="btn primary" type="submit">Build my plan</button></form>`)}
  function renewalOffer(){openModal('Add Virgin renewal offer',`<form id="renew-offer-form" class="form"><div class="field"><label>Monthly price Virgin offered</label><input id="ro-price" type="number" min="0" step="0.01" required value="${activeSession?.renewal_offer_price??''}"></div><div class="field"><label>Speed offered</label><input id="ro-speed" type="number" min="1" value="${activeSession?.renewal_offer_speed_mbps??''}"></div><div class="field"><label>Minimum term in months</label><input id="ro-term" type="number" min="1" max="36" value="${activeSession?.renewal_offer_term_months??24}"></div><div class="field"><label>Anything else included or promised?</label><textarea id="ro-notes" maxlength="1000">${s(activeSession?.renewal_offer_notes||'')}</textarea></div><button class="btn primary" type="submit">Compare this offer</button></form>`)}
  async function saveSession(data){if(!userId())return null;if(activeSession?.id){const rows=await api('vmusf_renewal_sessions?id=eq.'+encodeURIComponent(activeSession.id),{method:'PATCH',prefer:'return=representation',body:{...data,updated_at:new Date().toISOString()}});activeSession=rows?.[0]||activeSession;return activeSession}const rows=await api('vmusf_renewal_sessions',{method:'POST',prefer:'return=representation',body:{...data,user_id:userId()}});activeSession=rows?.[0]||null;return activeSession}
  function bestAlternative(speed){const pool=deals.filter(d=>!speed||Number(d.speed_mbps||0)>=Math.max(1,speed*.75));return pool.sort((a,b)=>Number(a.effective_monthly_price||a.monthly_price)-Number(b.effective_monthly_price||b.monthly_price))[0]||null}
  modalbody.addEventListener('submit',async e=>{if(e.target.id==='renew-start-form'){e.preventDefault();e.stopImmediatePropagation();const data={current_provider:'Virgin Media',current_monthly_price:Number(document.getElementById('rs-price').value),current_speed_mbps:Number(document.getElementById('rs-speed').value)||null,contract_end:document.getElementById('rs-end').value||null,target_monthly_price:Number(document.getElementById('rs-target').value)||null,priorities:{primary:document.getElementById('rs-priority').value},status:'comparing'};try{await saveSession(data)}catch(err){console.warn(err)}closeModal();render('deals');toastMsg(userId()?'Renewal plan saved.':'Renewal plan ready for this visit.')}if(e.target.id==='renew-offer-form'){e.preventDefault();e.stopImmediatePropagation();const p=Number(document.getElementById('ro-price').value),sp=Number(document.getElementById('ro-speed').value)||null,term=Number(document.getElementById('ro-term').value)||null,notes=document.getElementById('ro-notes').value.trim();try{await saveSession({renewal_offer_price:p,renewal_offer_speed_mbps:sp,renewal_offer_term_months:term,renewal_offer_notes:notes,status:'negotiating'})}catch(err){console.warn(err)}const alt=bestAlternative(sp),altPrice=alt?Number(alt.effective_monthly_price||alt.monthly_price):null,diff=altPrice===null?null:p-altPrice,u=alt?safeUrl(alt.source_url):'';openModal('Your negotiation position',`<div class="result"><h3>Check the whole offer before accepting.</h3><p class="lead">Virgin offered <b>${money(p)}/mo</b>${sp?' for '+sp+' Mbps':''}${term?' on a '+term+'-month term':''}.</p>${alt?`<div class="notice"><b>Useful comparison:</b> ${s(alt.provider)} currently has a verified ${s(alt.package_name)} record at ${money(altPrice)}/mo before address confirmation.${diff!==null&&diff>0?' That is '+money(diff)+' per month below the Virgin offer.':''}</div>`:''}<div class="notice good"><b>Suggested wording:</b><br>I’m happy to stay if the overall deal is competitive. I’ve checked current alternatives and I’d like you to review the best price you can offer for the services I actually need. Please confirm the monthly price, minimum term, any scheduled price changes, and exactly what is included before I decide.</div><p>Do not cancel simply to create pressure. Decide what you genuinely need, what price you would stay for, and what verified alternatives are actually available at your address.</p>${alt&&u?`<div class="actions"><a class="btn" href="${s(u)}" target="_blank" rel="noopener noreferrer">Check ${s(alt.provider)} directly</a></div>`:''}${notes?`<p><b>Your notes:</b> ${s(notes)}</p>`:''}</div>`)}},true);
  Promise.all([loadDeals(),loadSession()]).then(()=>{if(current==='deals')render('deals')});
})();