(() => {
  const uid=()=>window.VMUSF_AUTH?.user?.id||'';
  const token=()=>window.VMUSF_AUTH?.session?.access_token||'';
  const headers=(prefer='')=>({apikey:SUPABASE_KEY,'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{ }),...(prefer?{Prefer:prefer}:{})});
  async function dbx(path,{method='GET',body,prefer=''}={}){const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{method,headers:headers(prefer),body:body===undefined?undefined:JSON.stringify(body)});const t=await r.text();let d=null;if(t)try{d=JSON.parse(t)}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.details||d?.hint||('Request failed ('+r.status+')'));return d}
  const ex=s=>esc(String(s??''));
  async function isStaff(){if(!uid())return false;const r=await dbx('vmusf_staff?select=role,active&user_id=eq.'+encodeURIComponent(uid())+'&active=eq.true&limit=1').catch(()=>[]);return !!r?.[0]}
  async function openMemberActions(){if(!(await isStaff()))return toastMsg('Moderator access required.');openModal('Member actions',`<form class="form" id="vmusf-member-search"><div class="field"><label>Find member</label><input id="vmusf-member-q" required maxlength="40" placeholder="Username or display name"></div><button class="btn primary" type="submit">Find member</button></form><div id="vmusf-member-results"></div>`)}
  async function searchMember(term){const host=document.getElementById('vmusf-member-results');host.innerHTML='<div class="empty">Searching…</div>';try{const safe=term.replace(/[%,()]/g,' ').trim();const rows=await dbx('vmusf_profiles?select=user_id,display_name,username,bio&or=(username.ilike.*'+encodeURIComponent(safe)+'*,display_name.ilike.*'+encodeURIComponent(safe)+'*)&limit=12');host.innerHTML=(rows||[]).map(x=>`<button class="choice" data-member-action-id="${ex(x.user_id)}"><b>${ex(x.username?('@'+x.username):x.display_name)}</b><small>${ex(x.display_name)}${x.bio?' • '+ex(x.bio.slice(0,90)):''}</small></button>`).join('')||'<div class="empty">No matching members.</div>';host.querySelectorAll('[data-member-action-id]').forEach(b=>b.onclick=()=>memberActionPanel(b.dataset.memberActionId))}catch(e){host.innerHTML=`<div class="notice warn">${ex(e.message)}</div>`}}
  async function memberActionPanel(userId){try{const [p,s]=await Promise.all([dbx('vmusf_profiles?select=user_id,display_name,username,bio&user_id=eq.'+encodeURIComponent(userId)+'&limit=1'),dbx('vmusf_user_sanctions?select=id,sanction_type,reason,expires_at,created_at,revoked_at&user_id=eq.'+encodeURIComponent(userId)+'&order=created_at.desc&limit=20')]);const x=p?.[0]||{display_name:'VMUSF member'};openModal('Member actions',`<div class="result"><h3>${ex(x.username?('@'+x.username):x.display_name)}</h3><p>${ex(x.bio||'No bio.')}</p></div><form class="form" id="vmusf-sanction-form" data-user-id="${ex(userId)}"><div class="field"><label>Action</label><select id="vmusf-sanction-type"><option value="warning">Warning</option><option value="posting_suspension">Posting suspension</option></select></div><div class="field"><label>Reason</label><textarea id="vmusf-sanction-reason" maxlength="500" required placeholder="Explain the moderation reason clearly"></textarea></div><div class="field"><label>Suspension length</label><select id="vmusf-sanction-length"><option value="24">24 hours</option><option value="72">3 days</option><option value="168">7 days</option><option value="720">30 days</option></select></div><button class="btn danger" type="submit">Apply action</button></form><div class="splitline"></div><h3>Action history</h3><div class="form">${(s||[]).map(a=>`<div class="metric"><b>${a.sanction_type==='warning'?'Warning':'Posting suspension'}</b><small>${ex(a.reason)} • ${new Date(a.created_at).toLocaleString('en-GB')}${a.expires_at?' • until '+new Date(a.expires_at).toLocaleString('en-GB'):''}${a.revoked_at?' • revoked':''}</small>${!a.revoked_at?`<button class="btn ghost" data-revoke-sanction="${ex(a.id)}">Revoke</button>`:''}</div>`).join('')||'<div class="empty">No moderation actions.</div>'}</div>`);modalbody.querySelectorAll('[data-revoke-sanction]').forEach(b=>b.onclick=async()=>{await dbx('vmusf_user_sanctions?id=eq.'+encodeURIComponent(b.dataset.revokeSanction),{method:'PATCH',prefer:'return=minimal',body:{revoked_at:new Date().toISOString(),revoked_by:uid()}});memberActionPanel(userId);toastMsg('Moderation action revoked.')})}catch(e){toastMsg(e.message)}}
  modalbody.addEventListener('submit',async e=>{if(e.target.id==='vmusf-member-search'){e.preventDefault();e.stopImmediatePropagation();searchMember(document.getElementById('vmusf-member-q').value.trim())}else if(e.target.id==='vmusf-sanction-form'){e.preventDefault();e.stopImmediatePropagation();const type=document.getElementById('vmusf-sanction-type').value,hrs=Number(document.getElementById('vmusf-sanction-length').value),expires=type==='posting_suspension'?new Date(Date.now()+hrs*3600000).toISOString():null;try{await dbx('vmusf_user_sanctions',{method:'POST',prefer:'return=minimal',body:{user_id:e.target.dataset.userId,sanction_type:type,reason:document.getElementById('vmusf-sanction-reason').value.trim(),expires_at:expires,created_by:uid()}});toastMsg(type==='warning'?'Warning issued.':'Posting suspension applied.');memberActionPanel(e.target.dataset.userId)}catch(err){toastMsg(err.message)}}},true);
  const oldAction=action;action=function(a,d){if(a==='member-actions')return openMemberActions();return oldAction(a,d)};
  const obs=new MutationObserver(async()=>{if(current!=='account'||!uid())return;const side=document.querySelector('#app .side');if(!side||document.getElementById('vmusf-member-actions'))return;if(!(await isStaff()))return;const b=document.createElement('button');b.id='vmusf-member-actions';b.className='btn danger';b.textContent='Member actions';b.onclick=()=>openMemberActions();side.prepend(b)});obs.observe(document.body,{childList:true,subtree:true});
})();